/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/messages": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List stored conversation messages */
		get: operations["listMessages"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sessions": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List durable workspace sessions
		 * @description Lists every session this control surface holds. It takes no session header because it is how a client discovers which sessions exist.
		 */
		get: operations["listSessions"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sessions/open": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Open or resume the session for a workspace
		 * @description Resolves a workspace path to its one durable session, creating that session the first time the directory is opened. This is the only operation that creates a session, so a control surface starts with none and a client must name the workspace it wants. Opening the same directory again, by any of its names, resumes the existing session. A path outside every configured workspace root is refused with 403 and no session is created. A path beneath a configured root whose directory does not exist returns 404 WORKSPACE_NOT_FOUND.
		 */
		post: operations["openSession"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/execution-profiles": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List the execution profiles a client may name
		 * @description Lists the operator-defined profiles a session may run under. A client names a profile when it opens a workspace and never sends an image, mount, network setting, or capability. A profile that grants host-root-equivalent access carries a capability warning.
		 */
		get: operations["listExecutionProfiles"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/workspace-roots": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List workspace roots this controller may open
		 * @description Lists the operator-configured workspace roots available to this authenticated control surface. A client selects one of these roots when it opens its first session instead of guessing a host path. This is the deliberate, authenticated disclosure of the controller's workspace boundary; rejected workspace opens still disclose no roots.
		 */
		get: operations["listWorkspaceRoots"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/models": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List models discovered from configured connections
		 * @description Lists the non-secret model metadata Peen confirmed at controller startup. A model's name is the exact connection/model reference a WebSocket message.send frame may use for its one-turn model override.
		 */
		get: operations["listModels"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/workers": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List one session's worker generations
		 * @description Returns the durable worker generations for one session, newest first. A generation records the worker process that ran a set of turns, the profile revision it started under, and for a Docker generation its container and repository image digest when one is available.
		 */
		get: operations["listSessionWorkers"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/reconfigure": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Move an idle session to a different execution profile
		 * @description Changes the operator-defined profile a session's tools run under and records the decision with the caller's reason. The named profile must be one the operator defined; an undefined name is refused with 403. A session with a turn in flight is refused with 409, because changing the environment under running work would attribute that turn's tool calls to a profile that did not run them. On success the session's current worker is stopped, so the next turn starts a new generation under the new profile. The client names only a profile and never sends an image, mount, network setting, or capability.
		 */
		post: operations["reconfigureSession"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/profile-decisions": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List one session's execution profile decision history
		 * @description Returns the durable record of every execution profile change made to one session, newest first. Each entry names the profile the session moved from, the profile it moved to, and the reason the caller gave.
		 */
		get: operations["listSessionProfileDecisions"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Read session details */
		get: operations["getSession"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/cancel": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Request cancellation for the active turn */
		post: operations["cancelSession"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/events": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List durable protocol events */
		get: operations["listSessionEvents"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/notices": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List durable outside and worker notices */
		get: operations["listSessionNotices"];
		put?: never;
		/** Report a durable notice to the session */
		post: operations["publishSessionNotice"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/jobs": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List the commands this session has started */
		get: operations["listSessionJobs"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/jobs/{jobId}/output": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Read a bounded window of one job's output */
		get: operations["readSessionJobOutput"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/jobs/{jobId}/signals": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List the durable signal-request history for one job */
		get: operations["listSessionJobSignalRequests"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/jobs/{jobId}/signal": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Stop one running job */
		post: operations["signalSessionJob"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/agents": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List the child agent runs this session has started */
		get: operations["listSessionAgentRuns"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/turns": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List durable turns */
		get: operations["listSessionTurns"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/compactions": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List durable compaction records */
		get: operations["listSessionCompactions"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/compactions/{compactionId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Read one durable compaction record */
		get: operations["getSessionCompaction"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/model-runs": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List complete durable model invocations */
		get: operations["listSessionModelRuns"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/model-runs/{modelRunId}/calls": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Read every provider round for one model invocation */
		get: operations["listSessionModelRunCalls"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/context-snapshots/{contextHash}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Read a context snapshot referenced by this session */
		get: operations["getSessionContextSnapshot"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/prompt-snapshots/{promptHash}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Read a prompt snapshot referenced by this session */
		get: operations["getSessionPromptSnapshot"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/agents/{agentRunId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Read one durable child agent run */
		get: operations["getSessionAgentRun"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/agents/{agentRunId}/events": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Follow what one child agent run is doing */
		get: operations["listSessionAgentRunEvents"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/agents/{agentRunId}/messages": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List one child agent run's own durable transcript
		 * @description A child agent runs a separate model context, so its transcript is stored apart from the session transcript and is never absorbed by a parent-session compaction.
		 */
		get: operations["listSessionAgentRunMessages"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/agents/{agentRunId}/compactions": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List one child agent run's compaction lineage */
		get: operations["listSessionAgentRunCompactions"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/agents/{agentRunId}/compactions/{compactionId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Read one immutable child compaction record */
		get: operations["getSessionAgentRunCompaction"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session/agents/{agentRunId}/cancel": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Cancel one child agent run without ending its parent turn */
		post: operations["cancelSessionAgentRun"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		Message: {
			/** Format: uuid */
			id: string;
			/** Format: int64 */
			sequence: number;
			/** @enum {string} */
			role: "user" | "assistant" | "tool";
			content: string;
			workspace: string;
			model?: string | null;
			thinking?: string | null;
			toolCalls?: components["schemas"]["MessageToolCall"][] | null;
			toolCallId?: string | null;
			isError?: boolean;
			incomplete?: boolean;
			/** Format: uuid */
			compactionId?: string | null;
			/** Format: date-time */
			createdAt: string;
		};
		MessageToolCall: {
			id: string;
			name: string;
			arguments: {
				[key: string]: unknown;
			};
		};
		MessagePage: {
			items: components["schemas"]["Message"][];
			/** Format: int32 */
			limit: number;
			/** Format: int32 */
			offset: number;
			hasMore: boolean;
		};
		Session: {
			/** Format: uuid */
			id: string;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
			/** Format: date-time */
			lastMessageAt?: string | null;
			/** Format: int64 */
			messageCount: number;
			/** Format: int64 */
			completedTurnCount: number;
			activeTurn: boolean;
			agent: string;
			model: string;
			workspace: string;
			/** @description The operator-defined profile this session's tools run under. Empty for a session recorded before profiles existed, which the controller reads as the deployment default. */
			executionProfile?: string;
		};
		ExecutionProfile: {
			name: string;
			/** @enum {string} */
			kind: "native" | "docker";
			/** Format: int64 */
			revision: number;
			allowDockerSocket: boolean;
			allowNetwork: boolean;
			allowPrivilegeEscalation: boolean;
			/** @description True when this profile grants access that is effectively host root, such as a writable Docker socket. */
			hostRootEquivalent: boolean;
			/** @description Operator-facing warning for a host-root-equivalent profile. Empty for a profile that grants no such access. */
			capabilityWarning?: string;
		};
		ExecutionProfileList: {
			items: components["schemas"]["ExecutionProfile"][];
			/** @description The profile a session opened without naming one uses. */
			default: string;
		};
		WorkspaceRootList: {
			/** @description Canonical absolute directories the authenticated controller will accept as workspace roots. */
			roots: string[];
		};
		Model: {
			/** @description Exact connection/model reference accepted by message.send for a one-turn model override. */
			name: string;
			/** @description The configured connection portion of name. */
			connectionName: string;
			/** @description The raw model identifier the upstream accepted. */
			modelId: string;
			/**
			 * Format: int64
			 * @description The model context window Peen will enforce. For an upstream that publishes no window, this is the deployment context budget.
			 */
			contextWindowTokens: number;
		};
		ModelList: {
			/** @description Models available to this authenticated controller. */
			models: components["schemas"]["Model"][];
		};
		WebSocketMessageSystemPrompt: {
			content: string;
			/** @enum {string} */
			mode: "append" | "replace";
		};
		WebSocketMessageSendData: {
			message: string;
			/** @description Exact model name returned by GET /models, for this turn only. */
			model?: string;
			systemPrompt?: components["schemas"]["WebSocketMessageSystemPrompt"];
		};
		WebSocketMessageMetadata: {
			/** Format: uuid */
			sessionId: string;
		};
		WebSocketServerMetadata: {
			/** Format: uuid */
			sessionId?: string;
			/** Format: uuid */
			requestId?: string;
		};
		/** @description The only client-to-server WebSocket command. sessionId is routing metadata, not a permission grant. The server persists accepted work and broadcasts its resulting session events to all global sockets. */
		WebSocketMessageSendEvent: {
			/** Format: uuid */
			id: string;
			/** @constant */
			type: "message.send";
			data: components["schemas"]["WebSocketMessageSendData"];
			/** Format: int64 */
			timestamp: number;
			metadata: components["schemas"]["WebSocketMessageMetadata"];
			triggeredBy: null;
		};
		/** @description One Dabluvee event emitted by Peen. data is intentionally unknown at the envelope level because each native agent event type has its own payload. Clients preserve and render it without guessing its shape. */
		WebSocketServerEvent: {
			/** Format: uuid */
			id: string;
			type: string;
			data: unknown;
			/** Format: int64 */
			timestamp: number;
			metadata: components["schemas"]["WebSocketServerMetadata"];
			/** Format: uuid */
			triggeredBy: string | null;
		};
		WorkerGeneration: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			sessionId: string;
			/** @enum {string} */
			kind: "native" | "docker";
			profile: string;
			/** Format: int64 */
			profileRevision: number;
			/** @enum {string} */
			state: "requested" | "starting" | "ready" | "stopping" | "stopped" | "failed";
			workspace: string;
			/** @description Set only for a Docker generation. */
			containerId?: string;
			/** @description Immutable image identity for a Docker generation, never a moving tag. */
			imageDigest?: string;
			/** @description Why a generation failed or was replaced. Never carries credentials. */
			failureDetail?: string;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			startedAt?: string | null;
			/** Format: date-time */
			endedAt?: string | null;
		};
		ReconfigureSessionRequest: {
			/** @description The operator-defined profile to move this session to. An undefined name is refused. This is the only environment choice a client makes. */
			profile: string;
			/** @description Why the profile changed, kept in the durable decision history. */
			reason: string;
		};
		SessionProfileDecision: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			sessionId: string;
			/** @description The profile the session ran under before this decision. Absent when the session had no recorded profile. */
			fromProfile?: string;
			toProfile: string;
			reason: string;
			/** Format: date-time */
			decidedAt: string;
		};
		SessionProfileDecisionPage: {
			items: components["schemas"]["SessionProfileDecision"][];
			/** Format: int32 */
			limit: number;
			/** Format: int32 */
			offset: number;
			hasMore: boolean;
		};
		WorkerGenerationPage: {
			items: components["schemas"]["WorkerGeneration"][];
			/** Format: int32 */
			limit: number;
			/** Format: int32 */
			offset: number;
			hasMore: boolean;
		};
		SessionPage: {
			items: components["schemas"]["Session"][];
			/** Format: int32 */
			limit: number;
			/** Format: int32 */
			offset: number;
			hasMore: boolean;
		};
		OpenSessionRequest: {
			/** @description Absolute host path of the workspace directory. It is resolved through its symlinks and must fall under a configured workspace root. */
			workspace: string;
			/** @description Name of an operator-defined execution profile. Empty takes the deployment default. A name the operator did not define is refused with 403. This is the only environment choice a client makes: images, mounts, network, and capabilities come from deployment configuration alone. It applies only when this call creates the session; opening an existing session never changes its profile. */
			profile?: string;
		};
		OpenedSession: {
			session: components["schemas"]["Session"];
			/** @description True when this call created the session, false when it resumed an existing one. */
			created: boolean;
		};
		CancelResponse: {
			cancelRequested: boolean;
		};
		Turn: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			sessionId: string;
			/** Format: uuid */
			requestId: string;
			workspace: string;
			/** @enum {string} */
			state: "running" | "completed" | "failed" | "cancelled" | "interrupted";
			cancelRequested: boolean;
			/** Format: date-time */
			startedAt: string;
			/** Format: date-time */
			completedAt?: string | null;
			failureClassification: string;
			contextSnapshotHash?: string | null;
			promptSnapshotHash?: string | null;
		};
		TurnPage: {
			turns: components["schemas"]["Turn"][];
			/** Format: int32 */
			limit: number;
			/** Format: int32 */
			offset: number;
			hasMore: boolean;
		};
		TranscriptEvent: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			sessionId: string;
			/** Format: uuid */
			turnId: string;
			/** Format: int64 */
			sequence: number;
			/** Format: uuid */
			requestId: string;
			type: string;
			payload: {
				[key: string]: unknown;
			};
			parentToolCallId?: string | null;
			/** @description Worker generation that produced this event, if started. */
			workerGenerationId?: string | null;
			/** Format: date-time */
			createdAt: string;
		};
		TranscriptEventPage: {
			events: components["schemas"]["TranscriptEvent"][];
			/** Format: int32 */
			limit: number;
			/** Format: int32 */
			offset: number;
			hasMore: boolean;
		};
		/** @description One prompt-visible record in a child agent run's own transcript. It carries no turn: a child belongs to its agent run, not to a session turn's message sequence. */
		AgentRunMessage: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			sessionId: string;
			/** Format: uuid */
			agentRunId: string;
			/** Format: int64 */
			sequence: number;
			/** @enum {string} */
			role: "user" | "assistant" | "tool";
			content: string;
			model?: string;
			thinking?: string;
			toolCalls?: {
				[key: string]: unknown;
			}[];
			toolCallId?: string;
			/**
			 * Format: uuid
			 * @description The child compaction that directly covered this message, or null while it is still raw.
			 */
			compactionId?: string | null;
			isError: boolean;
			incomplete: boolean;
			/** Format: date-time */
			createdAt: string;
		};
		AgentRunMessagePage: {
			messages: components["schemas"]["AgentRunMessage"][];
			/** Format: int32 */
			limit: number;
			/** Format: int32 */
			offset: number;
			hasMore: boolean;
		};
		/** @description One immutable summary covering a completed prefix of one child agent run's transcript. directFromSequence and directToSequence name only the messages this row covered itself; fromSequence and toSequence span the whole superseded lineage. */
		AgentRunCompaction: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			sessionId: string;
			/** Format: uuid */
			agentRunId: string;
			/** Format: uuid */
			fromMessageId: string;
			/** Format: uuid */
			toMessageId: string;
			/** Format: int64 */
			fromSequence: number;
			/** Format: int64 */
			toSequence: number;
			/** Format: int64 */
			directFromSequence: number;
			/** Format: int64 */
			directToSequence: number;
			summary: string;
			/** Format: int64 */
			sourceMessageCount: number;
			/** Format: int64 */
			inputTokenCount: number;
			/** Format: int64 */
			summaryTokenCount: number;
			model: string;
			promptHash: string;
			/** Format: date-time */
			createdAt: string;
			/**
			 * Format: uuid
			 * @description The direct predecessor this compaction supersedes, or null for the first compaction in the chain.
			 */
			parentCompactionId?: string | null;
		};
		AgentRunCompactionPage: {
			compactions: components["schemas"]["AgentRunCompaction"][];
			/** Format: int32 */
			limit: number;
			/** Format: int32 */
			offset: number;
			hasMore: boolean;
		};
		Compaction: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			sessionId: string;
			/** Format: uuid */
			fromMessageId: string;
			/** Format: uuid */
			toMessageId: string;
			/** Format: int64 */
			fromSequence: number;
			/** Format: int64 */
			toSequence: number;
			summary: string;
			/** Format: int64 */
			sourceMessageCount: number;
			/** Format: int64 */
			inputTokenCount: number;
			/** Format: int64 */
			summaryTokenCount: number;
			model: string;
			promptHash: string;
			/** Format: date-time */
			createdAt: string;
			/** Format: uuid */
			parentCompactionId?: string | null;
		};
		CompactionPage: {
			compactions: components["schemas"]["Compaction"][];
			/** Format: int32 */
			limit: number;
			/** Format: int32 */
			offset: number;
			hasMore: boolean;
		};
		ModelRun: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			sessionId: string;
			/** Format: uuid */
			turnId: string;
			/** Format: uuid */
			agentRunId?: string | null;
			/** @enum {string} */
			stage: "turn" | "child" | "compaction";
			modelReference: string;
			connectionName: string;
			requestedModelId: string;
			responseModelId: string;
			requestSettings: {
				[key: string]: unknown;
			};
			/** @enum {string} */
			state: "running" | "completed" | "failed" | "cancelled" | "interrupted";
			responseText: string;
			responseThinking: string;
			responseMessages: unknown[];
			responseInjections: unknown[];
			responseUsage: {
				[key: string]: unknown;
			};
			responseCostAmount: string;
			retryCostAmount: string;
			billedCostAmount: string;
			costKnown: boolean;
			finishReason: string;
			failureClassification: string;
			failureDetail: string;
			/** Format: date-time */
			startedAt: string;
			/** Format: date-time */
			completedAt?: string | null;
		};
		ModelRunPage: {
			modelRuns: components["schemas"]["ModelRun"][];
			/** Format: int32 */
			limit: number;
			/** Format: int32 */
			offset: number;
			hasMore: boolean;
		};
		ModelCall: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			sessionId: string;
			/** Format: uuid */
			modelRunId: string;
			/** Format: int64 */
			round: number;
			requestMessages: unknown[];
			requestTools: unknown[];
			/** @enum {string} */
			state: "running" | "completed" | "failed" | "cancelled" | "interrupted";
			responseMessage: {
				[key: string]: unknown;
			} | null;
			responseUsage: {
				[key: string]: unknown;
			};
			retryAttempts: {
				[key: string]: unknown;
			}[];
			/** Format: int64 */
			retryAttemptCount: number;
			/** Format: int64 */
			promptTokens: number;
			/** Format: int64 */
			completionTokens: number;
			/** Format: int64 */
			totalTokens: number;
			/** Format: int64 */
			reasoningTokens: number;
			/** Format: int64 */
			cacheReadTokens: number;
			/** Format: int64 */
			cacheWriteTokens: number;
			/** Format: int64 */
			cacheWriteLongTtlTokens: number;
			/** Format: int64 */
			wastedPromptTokens: number;
			/** Format: int64 */
			wastedCompletionTokens: number;
			/** Format: int64 */
			wastedTotalTokens: number;
			/** Format: int64 */
			totalAttempts: number;
			responseModelId: string;
			finishReason: string;
			responseCostAmount: string;
			retryCostAmount: string;
			billedCostAmount: string;
			costKnown: boolean;
			failureClassification: string;
			failureDetail: string;
			/** Format: date-time */
			startedAt: string;
			/** Format: date-time */
			completedAt?: string | null;
		};
		ModelCallPage: {
			modelRun: components["schemas"]["ModelRun"];
			calls: components["schemas"]["ModelCall"][];
			/** Format: int32 */
			limit: number;
			/** Format: int32 */
			offset: number;
			hasMore: boolean;
		};
		ContextSnapshot: {
			hash: string;
			/** @description The layered sources this context was assembled from, in resolution order. It is a list because the harness contributes one entry per file from the filesystem root down to the workspace, and the same name may appear at more than one layer. */
			manifest: components["schemas"]["ContextManifestEntry"][];
			resolvedContent: string;
			/** Format: date-time */
			createdAt: string;
		};
		ContextManifestEntry: {
			kind: string;
			name: string;
			source: string;
			/** Format: int32 */
			priority: number;
			hash: string;
		};
		PromptSnapshot: {
			hash: string;
			effectivePrompt: string;
			/** Format: date-time */
			createdAt: string;
		};
		AgentRun: {
			/** Format: uuid */
			agentRunId: string;
			/** Format: uuid */
			sessionId: string;
			/** Format: uuid */
			parentTurnId: string;
			/** Format: uuid */
			parentAgentRunId?: string | null;
			/** @description Worker generation that ran this child agent. */
			workerGenerationId?: string | null;
			name: string;
			/** @enum {string} */
			definition: "stored" | "ad-hoc";
			parentToolCallId?: string | null;
			/** Format: uuid */
			requestId: string;
			/** Format: int64 */
			depth: number;
			workspace: string;
			modelReference: string;
			model: string;
			task: string;
			instructions: string;
			allowedTools: unknown[];
			systemPrompt: string;
			/** Format: int64 */
			eventCount: number;
			cancelRequested: boolean;
			/** @enum {string} */
			state: "running" | "completed" | "failed" | "cancelled" | "interrupted";
			responseText: string;
			responseThinking: string;
			responseMessages: unknown[];
			finishReason: string;
			/** Format: int64 */
			promptTokenCount: number;
			/** Format: int64 */
			completionTokenCount: number;
			failureClassification: string;
			failureDetail: string;
			/** Format: date-time */
			startedAt: string;
			/** Format: date-time */
			endedAt?: string | null;
		};
		AgentRunPage: {
			agents: components["schemas"]["AgentRun"][];
			/** Format: int32 */
			limit: number;
			/** Format: int32 */
			offset: number;
			hasMore: boolean;
		};
		AgentRunEvent: {
			/** Format: int64 */
			sequence: number;
			type: string;
			payload?: {
				[key: string]: unknown;
			};
			/** Format: date-time */
			createdAt: string;
		};
		AgentRunEventPage: {
			/** Format: uuid */
			agentRunId: string;
			/** @enum {string} */
			state: "running" | "completed" | "failed" | "cancelled" | "interrupted";
			events: components["schemas"]["AgentRunEvent"][];
			/**
			 * Format: int64
			 * @description Pass back as cursor to continue from here.
			 */
			nextCursor: number;
			hasMore: boolean;
		};
		AgentRunCancelResponse: {
			/** Format: uuid */
			agentRunId: string;
			/** @description True when this request found a running agent and signalled it. Cancelling an unknown, completed, or already cancelled run is not an error and reports false with the current state. */
			cancelRequested: boolean;
			/** @enum {string} */
			state: "running" | "completed" | "failed" | "cancelled" | "interrupted";
		};
		Job: {
			/** Format: uuid */
			jobId: string;
			/** Format: uuid */
			sessionId: string;
			/**
			 * Format: uuid
			 * @description The durable turn that launched this process.
			 */
			turnId: string;
			/**
			 * Format: int64
			 * @description Operating-system process ID of the job's shell.
			 */
			pid: number;
			/** @description Why the agent said it was running this command. */
			purpose: string;
			command: string;
			directory: string;
			/** @description The tool call that started this job. */
			toolCallId?: string;
			/** @description Worker generation that launched this process. */
			workerGenerationId?: string | null;
			/** @enum {string} */
			state: "running" | "exited" | "signalled" | "failed" | "interrupted";
			/** Format: date-time */
			startedAt: string;
			/** Format: date-time */
			endedAt?: string;
			/**
			 * Format: int64
			 * @description Exit status once known, or -1 while it is not.
			 */
			exitCode: number;
			/** @description Empty unless Peen recorded a terminal failure detail. */
			failureDetail: string;
		};
		JobPage: {
			jobs: components["schemas"]["Job"][];
			/** Format: int32 */
			limit: number;
			/** Format: int32 */
			offset: number;
			hasMore: boolean;
		};
		JobOutputLine: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			sessionId: string;
			/** Format: uuid */
			jobId: string;
			/** Format: int64 */
			sequence: number;
			/** @enum {string} */
			stream: "stdout" | "stderr";
			content: string;
			/** Format: date-time */
			createdAt: string;
		};
		JobOutput: {
			/** Format: uuid */
			jobId: string;
			/** @enum {string} */
			state: "running" | "exited" | "signalled" | "failed" | "interrupted";
			/** @description Ordered immutable stdout and stderr records from SQLite. */
			lines: components["schemas"]["JobOutputLine"][];
			/**
			 * Format: int64
			 * @description Pass back as cursor to continue from this durable sequence.
			 */
			nextCursor: number;
			hasMore: boolean;
		};
		JobSignalRequest: {
			/**
			 * @description stop sends SIGTERM to the process group then escalates to SIGKILL. kill goes straight to SIGKILL.
			 * @enum {string}
			 */
			signal: "stop" | "kill";
		};
		JobSignalRecord: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			sessionId: string;
			/** Format: uuid */
			jobId: string;
			/** @enum {string} */
			signal: "stop" | "kill";
			accepted: boolean;
			/** @enum {string} */
			stateAtRequest: "running" | "exited" | "signalled" | "failed" | "interrupted";
			/** Format: date-time */
			requestedAt: string;
		};
		JobSignalRecordPage: {
			job: components["schemas"]["Job"];
			signalRequests: components["schemas"]["JobSignalRecord"][];
			/** Format: int32 */
			limit: number;
			/** Format: int32 */
			offset: number;
			hasMore: boolean;
		};
		JobSignalResponse: {
			/** Format: uuid */
			jobId: string;
			/** @description True when this request found a running job and signalled it. Signalling an unknown, exited, or already signalled job is not an error and reports false with the current state. */
			signalled: boolean;
			/** @enum {string} */
			state: "running" | "exited" | "signalled" | "failed" | "interrupted";
		};
		SessionNoticeRequest: {
			/** @description Dotted lowercase namespaced type. The job. and agent. prefixes are reserved for Peen's own producers and are rejected here. */
			type: string;
			/** @description The one line describing what happened. */
			summary: string;
			/** @description Structured payload for programmatic consumers. */
			data?: {
				[key: string]: unknown;
			};
			/**
			 * @description queue waits for the next turn. wake starts a turn when the session is idle and .agents/events declares a handler for this type.
			 * @default queue
			 * @enum {string}
			 */
			delivery: "queue" | "wake";
		};
		SessionNotice: {
			/** Format: uuid */
			id: string;
			type: string;
			source: string;
			summary: string;
			data?: {
				[key: string]: unknown;
			};
			/** @enum {string} */
			delivery: "queue" | "wake";
			/** Format: date-time */
			createdAt: string;
		};
		SessionNoticePage: {
			notices: components["schemas"]["SessionNotice"][];
			/** Format: int32 */
			limit: number;
			/** Format: int32 */
			offset: number;
			hasMore: boolean;
		};
		Error: {
			code: string;
			message: string;
			details?: {
				[key: string]: unknown;
			};
		};
	};
	responses: {
		/** @description Invalid request */
		ErrorBadRequest: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["Error"];
			};
		};
		/** @description Authentication failed */
		ErrorUnauthorized: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["Error"];
			};
		};
		/** @description The request names a resource the deployment does not allow */
		ErrorForbidden: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["Error"];
			};
		};
		/** @description Requested resource not found */
		ErrorNotFound: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["Error"];
			};
		};
		/** @description Turn cannot run in its current state */
		ErrorConflict: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["Error"];
			};
		};
		/** @description Internal server error */
		ErrorInternal: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["Error"];
			};
		};
	};
	parameters: {
		SessionIDOptional: string;
		SessionIDRequired: string;
		AgentRunID: string;
		CompactionID: string;
		ModelRunID: string;
		ContextHash: string;
		PromptHash: string;
		JobID: string;
		Limit: number;
		Offset: number;
		Order: "asc" | "desc";
	};
	requestBodies: never;
	headers: {
		/** @description Created or resumed session UUID. */
		SessionID: string;
		/** @description Request correlation UUID. */
		RequestID: string;
	};
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	listMessages: {
		parameters: {
			query?: {
				limit?: components["parameters"]["Limit"];
				offset?: components["parameters"]["Offset"];
				order?: components["parameters"]["Order"];
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Message page */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MessagePage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listSessions: {
		parameters: {
			query?: {
				limit?: components["parameters"]["Limit"];
				offset?: components["parameters"]["Offset"];
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Session page */
			200: {
				headers: {
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionPage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	openSession: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["OpenSessionRequest"];
			};
		};
		responses: {
			/** @description Session opened or resumed */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["OpenedSession"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			403: components["responses"]["ErrorForbidden"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listExecutionProfiles: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Execution profile list */
			200: {
				headers: {
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ExecutionProfileList"];
				};
			};
			401: components["responses"]["ErrorUnauthorized"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listWorkspaceRoots: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Configured workspace root list */
			200: {
				headers: {
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WorkspaceRootList"];
				};
			};
			401: components["responses"]["ErrorUnauthorized"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listModels: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Discovered model list */
			200: {
				headers: {
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ModelList"];
				};
			};
			401: components["responses"]["ErrorUnauthorized"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listSessionWorkers: {
		parameters: {
			query?: {
				limit?: components["parameters"]["Limit"];
				offset?: components["parameters"]["Offset"];
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Worker generation page */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WorkerGenerationPage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	reconfigureSession: {
		parameters: {
			query?: never;
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ReconfigureSessionRequest"];
			};
		};
		responses: {
			/** @description Execution profile changed */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionProfileDecision"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			403: components["responses"]["ErrorForbidden"];
			404: components["responses"]["ErrorNotFound"];
			409: components["responses"]["ErrorConflict"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listSessionProfileDecisions: {
		parameters: {
			query?: {
				limit?: components["parameters"]["Limit"];
				offset?: components["parameters"]["Offset"];
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Execution profile decision page */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionProfileDecisionPage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	getSession: {
		parameters: {
			query?: never;
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Session details */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Session"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	cancelSession: {
		parameters: {
			query?: never;
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Cancellation request accepted */
			202: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CancelResponse"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listSessionEvents: {
		parameters: {
			query?: {
				limit?: components["parameters"]["Limit"];
				offset?: components["parameters"]["Offset"];
				order?: components["parameters"]["Order"];
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Durable protocol event page */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TranscriptEventPage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listSessionNotices: {
		parameters: {
			query?: {
				limit?: components["parameters"]["Limit"];
				offset?: components["parameters"]["Offset"];
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Notice page */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionNoticePage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	publishSessionNotice: {
		parameters: {
			query?: never;
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SessionNoticeRequest"];
			};
		};
		responses: {
			/** @description Notice accepted */
			202: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionNotice"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listSessionJobs: {
		parameters: {
			query?: {
				limit?: components["parameters"]["Limit"];
				offset?: components["parameters"]["Offset"];
				state?: "running" | "exited" | "signalled" | "failed" | "interrupted";
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Process jobs */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["JobPage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	readSessionJobOutput: {
		parameters: {
			query?: {
				stream?: "stdout" | "stderr" | "both";
				cursor?: number;
				limit?: number;
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path: {
				jobId: components["parameters"]["JobID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Job output window */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["JobOutput"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listSessionJobSignalRequests: {
		parameters: {
			query?: {
				limit?: components["parameters"]["Limit"];
				offset?: components["parameters"]["Offset"];
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path: {
				jobId: components["parameters"]["JobID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Job signal-request page */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["JobSignalRecordPage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	signalSessionJob: {
		parameters: {
			query?: never;
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path: {
				jobId: components["parameters"]["JobID"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["JobSignalRequest"];
			};
		};
		responses: {
			/** @description Signal accepted */
			202: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["JobSignalResponse"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listSessionAgentRuns: {
		parameters: {
			query?: {
				limit?: components["parameters"]["Limit"];
				offset?: components["parameters"]["Offset"];
				state?: "running" | "completed" | "failed" | "cancelled";
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Agent runs */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AgentRunPage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listSessionTurns: {
		parameters: {
			query?: {
				limit?: components["parameters"]["Limit"];
				offset?: components["parameters"]["Offset"];
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Turn page */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TurnPage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listSessionCompactions: {
		parameters: {
			query?: {
				limit?: components["parameters"]["Limit"];
				offset?: components["parameters"]["Offset"];
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Compaction page */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CompactionPage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	getSessionCompaction: {
		parameters: {
			query?: never;
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path: {
				compactionId: components["parameters"]["CompactionID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Compaction record */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Compaction"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listSessionModelRuns: {
		parameters: {
			query?: {
				limit?: components["parameters"]["Limit"];
				offset?: components["parameters"]["Offset"];
				stage?: "turn" | "child" | "compaction";
				state?: "running" | "completed" | "failed" | "cancelled" | "interrupted";
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Model invocation page */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ModelRunPage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listSessionModelRunCalls: {
		parameters: {
			query?: {
				limit?: components["parameters"]["Limit"];
				offset?: components["parameters"]["Offset"];
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path: {
				modelRunId: components["parameters"]["ModelRunID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Provider round page */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ModelCallPage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	getSessionContextSnapshot: {
		parameters: {
			query?: never;
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path: {
				contextHash: components["parameters"]["ContextHash"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Context snapshot */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ContextSnapshot"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	getSessionPromptSnapshot: {
		parameters: {
			query?: never;
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path: {
				promptHash: components["parameters"]["PromptHash"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Prompt snapshot */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PromptSnapshot"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	getSessionAgentRun: {
		parameters: {
			query?: never;
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path: {
				agentRunId: components["parameters"]["AgentRunID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Child agent run */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AgentRun"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listSessionAgentRunEvents: {
		parameters: {
			query?: {
				cursor?: number;
				limit?: number;
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path: {
				agentRunId: components["parameters"]["AgentRunID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Agent run events */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AgentRunEventPage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listSessionAgentRunMessages: {
		parameters: {
			query?: {
				limit?: components["parameters"]["Limit"];
				offset?: components["parameters"]["Offset"];
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path: {
				agentRunId: components["parameters"]["AgentRunID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Agent run message page */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AgentRunMessagePage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	listSessionAgentRunCompactions: {
		parameters: {
			query?: {
				limit?: components["parameters"]["Limit"];
				offset?: components["parameters"]["Offset"];
			};
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path: {
				agentRunId: components["parameters"]["AgentRunID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Agent run compaction page */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AgentRunCompactionPage"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	getSessionAgentRunCompaction: {
		parameters: {
			query?: never;
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path: {
				agentRunId: components["parameters"]["AgentRunID"];
				compactionId: components["parameters"]["CompactionID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Agent run compaction record */
			200: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AgentRunCompaction"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
	cancelSessionAgentRun: {
		parameters: {
			query?: never;
			header: {
				"X-Session-ID": components["parameters"]["SessionIDRequired"];
			};
			path: {
				agentRunId: components["parameters"]["AgentRunID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Cancellation request accepted */
			202: {
				headers: {
					"X-Session-ID": components["headers"]["SessionID"];
					"X-Request-ID": components["headers"]["RequestID"];
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AgentRunCancelResponse"];
				};
			};
			400: components["responses"]["ErrorBadRequest"];
			401: components["responses"]["ErrorUnauthorized"];
			404: components["responses"]["ErrorNotFound"];
			500: components["responses"]["ErrorInternal"];
		};
	};
}
