// Code generated by service_registration.sh; DO NOT EDIT.

package services

import (
	servicemanager "github.com/psyb0t/peen/internal/pkg/service-manager"
	controlapi "github.com/psyb0t/peen/internal/pkg/services/control-api"
	controlcore "github.com/psyb0t/peen/internal/pkg/services/control-core"
	helloworld "github.com/psyb0t/peen/internal/pkg/services/hello-world"
)

func Init() {
	sm := servicemanager.GetInstance()

	sm.Register(controlapi.ServiceName, func() (servicemanager.Service, error) {
		return controlapi.New()
	})

	sm.Register(controlcore.ServiceName, func() (servicemanager.Service, error) {
		return controlcore.New()
	})

	sm.Register(helloworld.ServiceName, func() (servicemanager.Service, error) {
		return helloworld.New()
	})

}
