// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/peen/internal/pkg/db/models"
)

func newAgentRunMessage(db *gorm.DB, opts ...gen.DOOption) agentRunMessage {
	_agentRunMessage := agentRunMessage{}

	_agentRunMessage.agentRunMessageDo.UseDB(db, opts...)
	_agentRunMessage.agentRunMessageDo.UseModel(&models.AgentRunMessage{})

	tableName := _agentRunMessage.agentRunMessageDo.TableName()
	_agentRunMessage.ALL = field.NewAsterisk(tableName)
	_agentRunMessage.ID = field.NewField(tableName, "id")
	_agentRunMessage.SessionID = field.NewField(tableName, "session_id")
	_agentRunMessage.AgentRunID = field.NewField(tableName, "agent_run_id")
	_agentRunMessage.Sequence = field.NewInt64(tableName, "sequence")
	_agentRunMessage.Role = field.NewString(tableName, "role")
	_agentRunMessage.Content = field.NewString(tableName, "content")
	_agentRunMessage.ModelID = field.NewString(tableName, "model_id")
	_agentRunMessage.Thinking = field.NewString(tableName, "thinking")
	_agentRunMessage.ToolCallsJSON = field.NewString(tableName, "tool_calls_json")
	_agentRunMessage.ToolCallID = field.NewString(tableName, "tool_call_id")
	_agentRunMessage.CompactionID = field.NewField(tableName, "compaction_id")
	_agentRunMessage.IsError = field.NewBool(tableName, "is_error")
	_agentRunMessage.Incomplete = field.NewBool(tableName, "incomplete")
	_agentRunMessage.CreatedAt = field.NewTime(tableName, "created_at")

	_agentRunMessage.fillFieldMap()

	return _agentRunMessage
}

type agentRunMessage struct {
	agentRunMessageDo

	ALL           field.Asterisk
	ID            field.Field
	SessionID     field.Field
	AgentRunID    field.Field
	Sequence      field.Int64
	Role          field.String
	Content       field.String
	ModelID       field.String
	Thinking      field.String
	ToolCallsJSON field.String
	ToolCallID    field.String
	CompactionID  field.Field
	IsError       field.Bool
	Incomplete    field.Bool
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (a agentRunMessage) Table(newTableName string) *agentRunMessage {
	a.agentRunMessageDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentRunMessage) As(alias string) *agentRunMessage {
	a.agentRunMessageDo.DO = *(a.agentRunMessageDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentRunMessage) updateTableName(table string) *agentRunMessage {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewField(table, "id")
	a.SessionID = field.NewField(table, "session_id")
	a.AgentRunID = field.NewField(table, "agent_run_id")
	a.Sequence = field.NewInt64(table, "sequence")
	a.Role = field.NewString(table, "role")
	a.Content = field.NewString(table, "content")
	a.ModelID = field.NewString(table, "model_id")
	a.Thinking = field.NewString(table, "thinking")
	a.ToolCallsJSON = field.NewString(table, "tool_calls_json")
	a.ToolCallID = field.NewString(table, "tool_call_id")
	a.CompactionID = field.NewField(table, "compaction_id")
	a.IsError = field.NewBool(table, "is_error")
	a.Incomplete = field.NewBool(table, "incomplete")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *agentRunMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentRunMessage) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 14)
	a.fieldMap["id"] = a.ID
	a.fieldMap["session_id"] = a.SessionID
	a.fieldMap["agent_run_id"] = a.AgentRunID
	a.fieldMap["sequence"] = a.Sequence
	a.fieldMap["role"] = a.Role
	a.fieldMap["content"] = a.Content
	a.fieldMap["model_id"] = a.ModelID
	a.fieldMap["thinking"] = a.Thinking
	a.fieldMap["tool_calls_json"] = a.ToolCallsJSON
	a.fieldMap["tool_call_id"] = a.ToolCallID
	a.fieldMap["compaction_id"] = a.CompactionID
	a.fieldMap["is_error"] = a.IsError
	a.fieldMap["incomplete"] = a.Incomplete
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a agentRunMessage) clone(db *gorm.DB) agentRunMessage {
	a.agentRunMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentRunMessage) replaceDB(db *gorm.DB) agentRunMessage {
	a.agentRunMessageDo.ReplaceDB(db)
	return a
}

type agentRunMessageDo struct{ gen.DO }

type IAgentRunMessageDo interface {
	gen.SubQuery
	Debug() IAgentRunMessageDo
	WithContext(ctx context.Context) IAgentRunMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAgentRunMessageDo
	WriteDB() IAgentRunMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAgentRunMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAgentRunMessageDo
	Not(conds ...gen.Condition) IAgentRunMessageDo
	Or(conds ...gen.Condition) IAgentRunMessageDo
	Select(conds ...field.Expr) IAgentRunMessageDo
	Where(conds ...gen.Condition) IAgentRunMessageDo
	Order(conds ...field.Expr) IAgentRunMessageDo
	Distinct(cols ...field.Expr) IAgentRunMessageDo
	Omit(cols ...field.Expr) IAgentRunMessageDo
	Join(table schema.Tabler, on ...field.Expr) IAgentRunMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAgentRunMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAgentRunMessageDo
	Group(cols ...field.Expr) IAgentRunMessageDo
	Having(conds ...gen.Condition) IAgentRunMessageDo
	Limit(limit int) IAgentRunMessageDo
	Offset(offset int) IAgentRunMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentRunMessageDo
	Unscoped() IAgentRunMessageDo
	Create(values ...*models.AgentRunMessage) error
	CreateInBatches(values []*models.AgentRunMessage, batchSize int) error
	Save(values ...*models.AgentRunMessage) error
	First() (*models.AgentRunMessage, error)
	Take() (*models.AgentRunMessage, error)
	Last() (*models.AgentRunMessage, error)
	Find() ([]*models.AgentRunMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentRunMessage, err error)
	FindInBatches(result *[]*models.AgentRunMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.AgentRunMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAgentRunMessageDo
	Assign(attrs ...field.AssignExpr) IAgentRunMessageDo
	Joins(fields ...field.RelationField) IAgentRunMessageDo
	Preload(fields ...field.RelationField) IAgentRunMessageDo
	FirstOrInit() (*models.AgentRunMessage, error)
	FirstOrCreate() (*models.AgentRunMessage, error)
	FindByPage(offset int, limit int) (result []*models.AgentRunMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAgentRunMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a agentRunMessageDo) Debug() IAgentRunMessageDo {
	return a.withDO(a.DO.Debug())
}

func (a agentRunMessageDo) WithContext(ctx context.Context) IAgentRunMessageDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a agentRunMessageDo) ReadDB() IAgentRunMessageDo {
	return a.Clauses(dbresolver.Read)
}

func (a agentRunMessageDo) WriteDB() IAgentRunMessageDo {
	return a.Clauses(dbresolver.Write)
}

func (a agentRunMessageDo) Session(config *gorm.Session) IAgentRunMessageDo {
	return a.withDO(a.DO.Session(config))
}

func (a agentRunMessageDo) Clauses(conds ...clause.Expression) IAgentRunMessageDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a agentRunMessageDo) Returning(value interface{}, columns ...string) IAgentRunMessageDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a agentRunMessageDo) Not(conds ...gen.Condition) IAgentRunMessageDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a agentRunMessageDo) Or(conds ...gen.Condition) IAgentRunMessageDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a agentRunMessageDo) Select(conds ...field.Expr) IAgentRunMessageDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a agentRunMessageDo) Where(conds ...gen.Condition) IAgentRunMessageDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a agentRunMessageDo) Order(conds ...field.Expr) IAgentRunMessageDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a agentRunMessageDo) Distinct(cols ...field.Expr) IAgentRunMessageDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a agentRunMessageDo) Omit(cols ...field.Expr) IAgentRunMessageDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a agentRunMessageDo) Join(table schema.Tabler, on ...field.Expr) IAgentRunMessageDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a agentRunMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAgentRunMessageDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a agentRunMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) IAgentRunMessageDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a agentRunMessageDo) Group(cols ...field.Expr) IAgentRunMessageDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a agentRunMessageDo) Having(conds ...gen.Condition) IAgentRunMessageDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a agentRunMessageDo) Limit(limit int) IAgentRunMessageDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a agentRunMessageDo) Offset(offset int) IAgentRunMessageDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a agentRunMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentRunMessageDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a agentRunMessageDo) Unscoped() IAgentRunMessageDo {
	return a.withDO(a.DO.Unscoped())
}

func (a agentRunMessageDo) Create(values ...*models.AgentRunMessage) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a agentRunMessageDo) CreateInBatches(values []*models.AgentRunMessage, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a agentRunMessageDo) Save(values ...*models.AgentRunMessage) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a agentRunMessageDo) First() (*models.AgentRunMessage, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRunMessage), nil
	}
}

func (a agentRunMessageDo) Take() (*models.AgentRunMessage, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRunMessage), nil
	}
}

func (a agentRunMessageDo) Last() (*models.AgentRunMessage, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRunMessage), nil
	}
}

func (a agentRunMessageDo) Find() ([]*models.AgentRunMessage, error) {
	result, err := a.DO.Find()
	return result.([]*models.AgentRunMessage), err
}

func (a agentRunMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentRunMessage, err error) {
	buf := make([]*models.AgentRunMessage, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a agentRunMessageDo) FindInBatches(result *[]*models.AgentRunMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a agentRunMessageDo) Attrs(attrs ...field.AssignExpr) IAgentRunMessageDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a agentRunMessageDo) Assign(attrs ...field.AssignExpr) IAgentRunMessageDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a agentRunMessageDo) Joins(fields ...field.RelationField) IAgentRunMessageDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a agentRunMessageDo) Preload(fields ...field.RelationField) IAgentRunMessageDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a agentRunMessageDo) FirstOrInit() (*models.AgentRunMessage, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRunMessage), nil
	}
}

func (a agentRunMessageDo) FirstOrCreate() (*models.AgentRunMessage, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRunMessage), nil
	}
}

func (a agentRunMessageDo) FindByPage(offset int, limit int) (result []*models.AgentRunMessage, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a agentRunMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a agentRunMessageDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a agentRunMessageDo) Delete(models ...*models.AgentRunMessage) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *agentRunMessageDo) withDO(do gen.Dao) *agentRunMessageDo {
	a.DO = *do.(*gen.DO)
	return a
}
