// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/peen/internal/pkg/db/models"

	"github.com/google/uuid"
)

func newAgentRunCompaction(db *gorm.DB, opts ...gen.DOOption) agentRunCompaction {
	_agentRunCompaction := agentRunCompaction{}

	_agentRunCompaction.agentRunCompactionDo.UseDB(db, opts...)
	_agentRunCompaction.agentRunCompactionDo.UseModel(&models.AgentRunCompaction{})

	tableName := _agentRunCompaction.agentRunCompactionDo.TableName()
	_agentRunCompaction.ALL = field.NewAsterisk(tableName)
	_agentRunCompaction.ID = field.NewField(tableName, "id")
	_agentRunCompaction.SessionID = field.NewField(tableName, "session_id")
	_agentRunCompaction.AgentRunID = field.NewField(tableName, "agent_run_id")
	_agentRunCompaction.FromMessageID = field.NewField(tableName, "from_message_id")
	_agentRunCompaction.ToMessageID = field.NewField(tableName, "to_message_id")
	_agentRunCompaction.FromSequence = field.NewInt64(tableName, "from_sequence")
	_agentRunCompaction.ToSequence = field.NewInt64(tableName, "to_sequence")
	_agentRunCompaction.DirectFromSequence = field.NewInt64(tableName, "direct_from_sequence")
	_agentRunCompaction.DirectToSequence = field.NewInt64(tableName, "direct_to_sequence")
	_agentRunCompaction.Summary = field.NewString(tableName, "summary")
	_agentRunCompaction.SourceMessageCount = field.NewInt64(tableName, "source_message_count")
	_agentRunCompaction.InputTokenCount = field.NewInt64(tableName, "input_token_count")
	_agentRunCompaction.SummaryTokenCount = field.NewInt64(tableName, "summary_token_count")
	_agentRunCompaction.ModelID = field.NewString(tableName, "model_id")
	_agentRunCompaction.PromptHash = field.NewString(tableName, "prompt_hash")
	_agentRunCompaction.CreatedAt = field.NewTime(tableName, "created_at")
	_agentRunCompaction.SupersedesCompactionID = field.NewField(tableName, "supersedes_compaction_id")

	_agentRunCompaction.fillFieldMap()

	return _agentRunCompaction
}

type agentRunCompaction struct {
	agentRunCompactionDo

	ALL                    field.Asterisk
	ID                     field.Field
	SessionID              field.Field
	AgentRunID             field.Field
	FromMessageID          field.Field
	ToMessageID            field.Field
	FromSequence           field.Int64
	ToSequence             field.Int64
	DirectFromSequence     field.Int64
	DirectToSequence       field.Int64
	Summary                field.String
	SourceMessageCount     field.Int64
	InputTokenCount        field.Int64
	SummaryTokenCount      field.Int64
	ModelID                field.String
	PromptHash             field.String
	CreatedAt              field.Time
	SupersedesCompactionID field.Field

	fieldMap map[string]field.Expr
}

func (a agentRunCompaction) Table(newTableName string) *agentRunCompaction {
	a.agentRunCompactionDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentRunCompaction) As(alias string) *agentRunCompaction {
	a.agentRunCompactionDo.DO = *(a.agentRunCompactionDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentRunCompaction) updateTableName(table string) *agentRunCompaction {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewField(table, "id")
	a.SessionID = field.NewField(table, "session_id")
	a.AgentRunID = field.NewField(table, "agent_run_id")
	a.FromMessageID = field.NewField(table, "from_message_id")
	a.ToMessageID = field.NewField(table, "to_message_id")
	a.FromSequence = field.NewInt64(table, "from_sequence")
	a.ToSequence = field.NewInt64(table, "to_sequence")
	a.DirectFromSequence = field.NewInt64(table, "direct_from_sequence")
	a.DirectToSequence = field.NewInt64(table, "direct_to_sequence")
	a.Summary = field.NewString(table, "summary")
	a.SourceMessageCount = field.NewInt64(table, "source_message_count")
	a.InputTokenCount = field.NewInt64(table, "input_token_count")
	a.SummaryTokenCount = field.NewInt64(table, "summary_token_count")
	a.ModelID = field.NewString(table, "model_id")
	a.PromptHash = field.NewString(table, "prompt_hash")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.SupersedesCompactionID = field.NewField(table, "supersedes_compaction_id")

	a.fillFieldMap()

	return a
}

func (a *agentRunCompaction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentRunCompaction) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 17)
	a.fieldMap["id"] = a.ID
	a.fieldMap["session_id"] = a.SessionID
	a.fieldMap["agent_run_id"] = a.AgentRunID
	a.fieldMap["from_message_id"] = a.FromMessageID
	a.fieldMap["to_message_id"] = a.ToMessageID
	a.fieldMap["from_sequence"] = a.FromSequence
	a.fieldMap["to_sequence"] = a.ToSequence
	a.fieldMap["direct_from_sequence"] = a.DirectFromSequence
	a.fieldMap["direct_to_sequence"] = a.DirectToSequence
	a.fieldMap["summary"] = a.Summary
	a.fieldMap["source_message_count"] = a.SourceMessageCount
	a.fieldMap["input_token_count"] = a.InputTokenCount
	a.fieldMap["summary_token_count"] = a.SummaryTokenCount
	a.fieldMap["model_id"] = a.ModelID
	a.fieldMap["prompt_hash"] = a.PromptHash
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["supersedes_compaction_id"] = a.SupersedesCompactionID
}

func (a agentRunCompaction) clone(db *gorm.DB) agentRunCompaction {
	a.agentRunCompactionDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentRunCompaction) replaceDB(db *gorm.DB) agentRunCompaction {
	a.agentRunCompactionDo.ReplaceDB(db)
	return a
}

type agentRunCompactionDo struct{ gen.DO }

type IAgentRunCompactionDo interface {
	gen.SubQuery
	Debug() IAgentRunCompactionDo
	WithContext(ctx context.Context) IAgentRunCompactionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAgentRunCompactionDo
	WriteDB() IAgentRunCompactionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAgentRunCompactionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAgentRunCompactionDo
	Not(conds ...gen.Condition) IAgentRunCompactionDo
	Or(conds ...gen.Condition) IAgentRunCompactionDo
	Select(conds ...field.Expr) IAgentRunCompactionDo
	Where(conds ...gen.Condition) IAgentRunCompactionDo
	Order(conds ...field.Expr) IAgentRunCompactionDo
	Distinct(cols ...field.Expr) IAgentRunCompactionDo
	Omit(cols ...field.Expr) IAgentRunCompactionDo
	Join(table schema.Tabler, on ...field.Expr) IAgentRunCompactionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAgentRunCompactionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAgentRunCompactionDo
	Group(cols ...field.Expr) IAgentRunCompactionDo
	Having(conds ...gen.Condition) IAgentRunCompactionDo
	Limit(limit int) IAgentRunCompactionDo
	Offset(offset int) IAgentRunCompactionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentRunCompactionDo
	Unscoped() IAgentRunCompactionDo
	Create(values ...*models.AgentRunCompaction) error
	CreateInBatches(values []*models.AgentRunCompaction, batchSize int) error
	Save(values ...*models.AgentRunCompaction) error
	First() (*models.AgentRunCompaction, error)
	Take() (*models.AgentRunCompaction, error)
	Last() (*models.AgentRunCompaction, error)
	Find() ([]*models.AgentRunCompaction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentRunCompaction, err error)
	FindInBatches(result *[]*models.AgentRunCompaction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.AgentRunCompaction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAgentRunCompactionDo
	Assign(attrs ...field.AssignExpr) IAgentRunCompactionDo
	Joins(fields ...field.RelationField) IAgentRunCompactionDo
	Preload(fields ...field.RelationField) IAgentRunCompactionDo
	FirstOrInit() (*models.AgentRunCompaction, error)
	FirstOrCreate() (*models.AgentRunCompaction, error)
	FindByPage(offset int, limit int) (result []*models.AgentRunCompaction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAgentRunCompactionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	ActiveHead(agentRunID uuid.UUID) (result *models.AgentRunCompaction, err error)
}

// SELECT current.*
//
//	FROM agent_run_compactions AS current
//	WHERE current.agent_run_id = @agentRunID
//	  AND NOT EXISTS (
//		  SELECT 1
//		  FROM agent_run_compactions AS newer
//		  WHERE newer.agent_run_id = current.agent_run_id
//		    AND newer.supersedes_compaction_id = current.id
//	  )
//	ORDER BY current.to_sequence DESC, current.id DESC
//	LIMIT 1
func (a agentRunCompactionDo) ActiveHead(agentRunID uuid.UUID) (result *models.AgentRunCompaction, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, agentRunID)
	generateSQL.WriteString("SELECT current.* FROM agent_run_compactions AS current WHERE current.agent_run_id = ? AND NOT EXISTS ( SELECT 1 FROM agent_run_compactions AS newer WHERE newer.agent_run_id = current.agent_run_id AND newer.supersedes_compaction_id = current.id ) ORDER BY current.to_sequence DESC, current.id DESC LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (a agentRunCompactionDo) Debug() IAgentRunCompactionDo {
	return a.withDO(a.DO.Debug())
}

func (a agentRunCompactionDo) WithContext(ctx context.Context) IAgentRunCompactionDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a agentRunCompactionDo) ReadDB() IAgentRunCompactionDo {
	return a.Clauses(dbresolver.Read)
}

func (a agentRunCompactionDo) WriteDB() IAgentRunCompactionDo {
	return a.Clauses(dbresolver.Write)
}

func (a agentRunCompactionDo) Session(config *gorm.Session) IAgentRunCompactionDo {
	return a.withDO(a.DO.Session(config))
}

func (a agentRunCompactionDo) Clauses(conds ...clause.Expression) IAgentRunCompactionDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a agentRunCompactionDo) Returning(value interface{}, columns ...string) IAgentRunCompactionDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a agentRunCompactionDo) Not(conds ...gen.Condition) IAgentRunCompactionDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a agentRunCompactionDo) Or(conds ...gen.Condition) IAgentRunCompactionDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a agentRunCompactionDo) Select(conds ...field.Expr) IAgentRunCompactionDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a agentRunCompactionDo) Where(conds ...gen.Condition) IAgentRunCompactionDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a agentRunCompactionDo) Order(conds ...field.Expr) IAgentRunCompactionDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a agentRunCompactionDo) Distinct(cols ...field.Expr) IAgentRunCompactionDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a agentRunCompactionDo) Omit(cols ...field.Expr) IAgentRunCompactionDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a agentRunCompactionDo) Join(table schema.Tabler, on ...field.Expr) IAgentRunCompactionDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a agentRunCompactionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAgentRunCompactionDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a agentRunCompactionDo) RightJoin(table schema.Tabler, on ...field.Expr) IAgentRunCompactionDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a agentRunCompactionDo) Group(cols ...field.Expr) IAgentRunCompactionDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a agentRunCompactionDo) Having(conds ...gen.Condition) IAgentRunCompactionDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a agentRunCompactionDo) Limit(limit int) IAgentRunCompactionDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a agentRunCompactionDo) Offset(offset int) IAgentRunCompactionDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a agentRunCompactionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentRunCompactionDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a agentRunCompactionDo) Unscoped() IAgentRunCompactionDo {
	return a.withDO(a.DO.Unscoped())
}

func (a agentRunCompactionDo) Create(values ...*models.AgentRunCompaction) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a agentRunCompactionDo) CreateInBatches(values []*models.AgentRunCompaction, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a agentRunCompactionDo) Save(values ...*models.AgentRunCompaction) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a agentRunCompactionDo) First() (*models.AgentRunCompaction, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRunCompaction), nil
	}
}

func (a agentRunCompactionDo) Take() (*models.AgentRunCompaction, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRunCompaction), nil
	}
}

func (a agentRunCompactionDo) Last() (*models.AgentRunCompaction, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRunCompaction), nil
	}
}

func (a agentRunCompactionDo) Find() ([]*models.AgentRunCompaction, error) {
	result, err := a.DO.Find()
	return result.([]*models.AgentRunCompaction), err
}

func (a agentRunCompactionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentRunCompaction, err error) {
	buf := make([]*models.AgentRunCompaction, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a agentRunCompactionDo) FindInBatches(result *[]*models.AgentRunCompaction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a agentRunCompactionDo) Attrs(attrs ...field.AssignExpr) IAgentRunCompactionDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a agentRunCompactionDo) Assign(attrs ...field.AssignExpr) IAgentRunCompactionDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a agentRunCompactionDo) Joins(fields ...field.RelationField) IAgentRunCompactionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a agentRunCompactionDo) Preload(fields ...field.RelationField) IAgentRunCompactionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a agentRunCompactionDo) FirstOrInit() (*models.AgentRunCompaction, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRunCompaction), nil
	}
}

func (a agentRunCompactionDo) FirstOrCreate() (*models.AgentRunCompaction, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRunCompaction), nil
	}
}

func (a agentRunCompactionDo) FindByPage(offset int, limit int) (result []*models.AgentRunCompaction, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a agentRunCompactionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a agentRunCompactionDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a agentRunCompactionDo) Delete(models ...*models.AgentRunCompaction) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *agentRunCompactionDo) withDO(do gen.Dao) *agentRunCompactionDo {
	a.DO = *do.(*gen.DO)
	return a
}
