// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/peen/internal/pkg/db/models"
)

func newAgentRun(db *gorm.DB, opts ...gen.DOOption) agentRun {
	_agentRun := agentRun{}

	_agentRun.agentRunDo.UseDB(db, opts...)
	_agentRun.agentRunDo.UseModel(&models.AgentRun{})

	tableName := _agentRun.agentRunDo.TableName()
	_agentRun.ALL = field.NewAsterisk(tableName)
	_agentRun.ID = field.NewField(tableName, "id")
	_agentRun.SessionID = field.NewField(tableName, "session_id")
	_agentRun.ParentTurnID = field.NewField(tableName, "parent_turn_id")
	_agentRun.ParentAgentRunID = field.NewField(tableName, "parent_agent_run_id")
	_agentRun.ParentToolCallID = field.NewString(tableName, "parent_tool_call_id")
	_agentRun.RequestID = field.NewField(tableName, "request_id")
	_agentRun.Name = field.NewString(tableName, "name")
	_agentRun.Definition = field.NewString(tableName, "definition")
	_agentRun.Depth = field.NewInt64(tableName, "depth")
	_agentRun.Workspace = field.NewString(tableName, "workspace")
	_agentRun.ModelReference = field.NewString(tableName, "model_reference")
	_agentRun.ModelID = field.NewString(tableName, "model_id")
	_agentRun.Task = field.NewString(tableName, "task")
	_agentRun.Instructions = field.NewString(tableName, "instructions")
	_agentRun.AllowedToolsJSON = field.NewString(tableName, "allowed_tools_json")
	_agentRun.SystemPrompt = field.NewString(tableName, "system_prompt")
	_agentRun.EventCount = field.NewInt64(tableName, "event_count")
	_agentRun.CancelRequested = field.NewBool(tableName, "cancel_requested")
	_agentRun.State = field.NewString(tableName, "state")
	_agentRun.ResponseText = field.NewString(tableName, "response_text")
	_agentRun.ResponseThinking = field.NewString(tableName, "response_thinking")
	_agentRun.ResponseMessagesJSON = field.NewString(tableName, "response_messages_json")
	_agentRun.FinishReason = field.NewString(tableName, "finish_reason")
	_agentRun.PromptTokenCount = field.NewInt64(tableName, "prompt_token_count")
	_agentRun.CompletionTokenCount = field.NewInt64(tableName, "completion_token_count")
	_agentRun.FailureClassification = field.NewString(tableName, "failure_classification")
	_agentRun.FailureDetail = field.NewString(tableName, "failure_detail")
	_agentRun.StartedAt = field.NewTime(tableName, "started_at")
	_agentRun.EndedAt = field.NewTime(tableName, "ended_at")

	_agentRun.fillFieldMap()

	return _agentRun
}

type agentRun struct {
	agentRunDo

	ALL                   field.Asterisk
	ID                    field.Field
	SessionID             field.Field
	ParentTurnID          field.Field
	ParentAgentRunID      field.Field
	ParentToolCallID      field.String
	RequestID             field.Field
	Name                  field.String
	Definition            field.String
	Depth                 field.Int64
	Workspace             field.String
	ModelReference        field.String
	ModelID               field.String
	Task                  field.String
	Instructions          field.String
	AllowedToolsJSON      field.String
	SystemPrompt          field.String
	EventCount            field.Int64
	CancelRequested       field.Bool
	State                 field.String
	ResponseText          field.String
	ResponseThinking      field.String
	ResponseMessagesJSON  field.String
	FinishReason          field.String
	PromptTokenCount      field.Int64
	CompletionTokenCount  field.Int64
	FailureClassification field.String
	FailureDetail         field.String
	StartedAt             field.Time
	EndedAt               field.Time

	fieldMap map[string]field.Expr
}

func (a agentRun) Table(newTableName string) *agentRun {
	a.agentRunDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentRun) As(alias string) *agentRun {
	a.agentRunDo.DO = *(a.agentRunDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentRun) updateTableName(table string) *agentRun {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewField(table, "id")
	a.SessionID = field.NewField(table, "session_id")
	a.ParentTurnID = field.NewField(table, "parent_turn_id")
	a.ParentAgentRunID = field.NewField(table, "parent_agent_run_id")
	a.ParentToolCallID = field.NewString(table, "parent_tool_call_id")
	a.RequestID = field.NewField(table, "request_id")
	a.Name = field.NewString(table, "name")
	a.Definition = field.NewString(table, "definition")
	a.Depth = field.NewInt64(table, "depth")
	a.Workspace = field.NewString(table, "workspace")
	a.ModelReference = field.NewString(table, "model_reference")
	a.ModelID = field.NewString(table, "model_id")
	a.Task = field.NewString(table, "task")
	a.Instructions = field.NewString(table, "instructions")
	a.AllowedToolsJSON = field.NewString(table, "allowed_tools_json")
	a.SystemPrompt = field.NewString(table, "system_prompt")
	a.EventCount = field.NewInt64(table, "event_count")
	a.CancelRequested = field.NewBool(table, "cancel_requested")
	a.State = field.NewString(table, "state")
	a.ResponseText = field.NewString(table, "response_text")
	a.ResponseThinking = field.NewString(table, "response_thinking")
	a.ResponseMessagesJSON = field.NewString(table, "response_messages_json")
	a.FinishReason = field.NewString(table, "finish_reason")
	a.PromptTokenCount = field.NewInt64(table, "prompt_token_count")
	a.CompletionTokenCount = field.NewInt64(table, "completion_token_count")
	a.FailureClassification = field.NewString(table, "failure_classification")
	a.FailureDetail = field.NewString(table, "failure_detail")
	a.StartedAt = field.NewTime(table, "started_at")
	a.EndedAt = field.NewTime(table, "ended_at")

	a.fillFieldMap()

	return a
}

func (a *agentRun) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentRun) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 29)
	a.fieldMap["id"] = a.ID
	a.fieldMap["session_id"] = a.SessionID
	a.fieldMap["parent_turn_id"] = a.ParentTurnID
	a.fieldMap["parent_agent_run_id"] = a.ParentAgentRunID
	a.fieldMap["parent_tool_call_id"] = a.ParentToolCallID
	a.fieldMap["request_id"] = a.RequestID
	a.fieldMap["name"] = a.Name
	a.fieldMap["definition"] = a.Definition
	a.fieldMap["depth"] = a.Depth
	a.fieldMap["workspace"] = a.Workspace
	a.fieldMap["model_reference"] = a.ModelReference
	a.fieldMap["model_id"] = a.ModelID
	a.fieldMap["task"] = a.Task
	a.fieldMap["instructions"] = a.Instructions
	a.fieldMap["allowed_tools_json"] = a.AllowedToolsJSON
	a.fieldMap["system_prompt"] = a.SystemPrompt
	a.fieldMap["event_count"] = a.EventCount
	a.fieldMap["cancel_requested"] = a.CancelRequested
	a.fieldMap["state"] = a.State
	a.fieldMap["response_text"] = a.ResponseText
	a.fieldMap["response_thinking"] = a.ResponseThinking
	a.fieldMap["response_messages_json"] = a.ResponseMessagesJSON
	a.fieldMap["finish_reason"] = a.FinishReason
	a.fieldMap["prompt_token_count"] = a.PromptTokenCount
	a.fieldMap["completion_token_count"] = a.CompletionTokenCount
	a.fieldMap["failure_classification"] = a.FailureClassification
	a.fieldMap["failure_detail"] = a.FailureDetail
	a.fieldMap["started_at"] = a.StartedAt
	a.fieldMap["ended_at"] = a.EndedAt
}

func (a agentRun) clone(db *gorm.DB) agentRun {
	a.agentRunDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentRun) replaceDB(db *gorm.DB) agentRun {
	a.agentRunDo.ReplaceDB(db)
	return a
}

type agentRunDo struct{ gen.DO }

type IAgentRunDo interface {
	gen.SubQuery
	Debug() IAgentRunDo
	WithContext(ctx context.Context) IAgentRunDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAgentRunDo
	WriteDB() IAgentRunDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAgentRunDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAgentRunDo
	Not(conds ...gen.Condition) IAgentRunDo
	Or(conds ...gen.Condition) IAgentRunDo
	Select(conds ...field.Expr) IAgentRunDo
	Where(conds ...gen.Condition) IAgentRunDo
	Order(conds ...field.Expr) IAgentRunDo
	Distinct(cols ...field.Expr) IAgentRunDo
	Omit(cols ...field.Expr) IAgentRunDo
	Join(table schema.Tabler, on ...field.Expr) IAgentRunDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAgentRunDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAgentRunDo
	Group(cols ...field.Expr) IAgentRunDo
	Having(conds ...gen.Condition) IAgentRunDo
	Limit(limit int) IAgentRunDo
	Offset(offset int) IAgentRunDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentRunDo
	Unscoped() IAgentRunDo
	Create(values ...*models.AgentRun) error
	CreateInBatches(values []*models.AgentRun, batchSize int) error
	Save(values ...*models.AgentRun) error
	First() (*models.AgentRun, error)
	Take() (*models.AgentRun, error)
	Last() (*models.AgentRun, error)
	Find() ([]*models.AgentRun, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentRun, err error)
	FindInBatches(result *[]*models.AgentRun, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.AgentRun) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAgentRunDo
	Assign(attrs ...field.AssignExpr) IAgentRunDo
	Joins(fields ...field.RelationField) IAgentRunDo
	Preload(fields ...field.RelationField) IAgentRunDo
	FirstOrInit() (*models.AgentRun, error)
	FirstOrCreate() (*models.AgentRun, error)
	FindByPage(offset int, limit int) (result []*models.AgentRun, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAgentRunDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a agentRunDo) Debug() IAgentRunDo {
	return a.withDO(a.DO.Debug())
}

func (a agentRunDo) WithContext(ctx context.Context) IAgentRunDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a agentRunDo) ReadDB() IAgentRunDo {
	return a.Clauses(dbresolver.Read)
}

func (a agentRunDo) WriteDB() IAgentRunDo {
	return a.Clauses(dbresolver.Write)
}

func (a agentRunDo) Session(config *gorm.Session) IAgentRunDo {
	return a.withDO(a.DO.Session(config))
}

func (a agentRunDo) Clauses(conds ...clause.Expression) IAgentRunDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a agentRunDo) Returning(value interface{}, columns ...string) IAgentRunDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a agentRunDo) Not(conds ...gen.Condition) IAgentRunDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a agentRunDo) Or(conds ...gen.Condition) IAgentRunDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a agentRunDo) Select(conds ...field.Expr) IAgentRunDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a agentRunDo) Where(conds ...gen.Condition) IAgentRunDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a agentRunDo) Order(conds ...field.Expr) IAgentRunDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a agentRunDo) Distinct(cols ...field.Expr) IAgentRunDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a agentRunDo) Omit(cols ...field.Expr) IAgentRunDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a agentRunDo) Join(table schema.Tabler, on ...field.Expr) IAgentRunDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a agentRunDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAgentRunDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a agentRunDo) RightJoin(table schema.Tabler, on ...field.Expr) IAgentRunDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a agentRunDo) Group(cols ...field.Expr) IAgentRunDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a agentRunDo) Having(conds ...gen.Condition) IAgentRunDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a agentRunDo) Limit(limit int) IAgentRunDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a agentRunDo) Offset(offset int) IAgentRunDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a agentRunDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentRunDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a agentRunDo) Unscoped() IAgentRunDo {
	return a.withDO(a.DO.Unscoped())
}

func (a agentRunDo) Create(values ...*models.AgentRun) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a agentRunDo) CreateInBatches(values []*models.AgentRun, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a agentRunDo) Save(values ...*models.AgentRun) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a agentRunDo) First() (*models.AgentRun, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRun), nil
	}
}

func (a agentRunDo) Take() (*models.AgentRun, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRun), nil
	}
}

func (a agentRunDo) Last() (*models.AgentRun, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRun), nil
	}
}

func (a agentRunDo) Find() ([]*models.AgentRun, error) {
	result, err := a.DO.Find()
	return result.([]*models.AgentRun), err
}

func (a agentRunDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentRun, err error) {
	buf := make([]*models.AgentRun, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a agentRunDo) FindInBatches(result *[]*models.AgentRun, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a agentRunDo) Attrs(attrs ...field.AssignExpr) IAgentRunDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a agentRunDo) Assign(attrs ...field.AssignExpr) IAgentRunDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a agentRunDo) Joins(fields ...field.RelationField) IAgentRunDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a agentRunDo) Preload(fields ...field.RelationField) IAgentRunDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a agentRunDo) FirstOrInit() (*models.AgentRun, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRun), nil
	}
}

func (a agentRunDo) FirstOrCreate() (*models.AgentRun, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRun), nil
	}
}

func (a agentRunDo) FindByPage(offset int, limit int) (result []*models.AgentRun, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a agentRunDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a agentRunDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a agentRunDo) Delete(models ...*models.AgentRun) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *agentRunDo) withDO(do gen.Dao) *agentRunDo {
	a.DO = *do.(*gen.DO)
	return a
}
