// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/peen/internal/pkg/db/models"
)

func newAgentRunEvent(db *gorm.DB, opts ...gen.DOOption) agentRunEvent {
	_agentRunEvent := agentRunEvent{}

	_agentRunEvent.agentRunEventDo.UseDB(db, opts...)
	_agentRunEvent.agentRunEventDo.UseModel(&models.AgentRunEvent{})

	tableName := _agentRunEvent.agentRunEventDo.TableName()
	_agentRunEvent.ALL = field.NewAsterisk(tableName)
	_agentRunEvent.ID = field.NewField(tableName, "id")
	_agentRunEvent.SessionID = field.NewField(tableName, "session_id")
	_agentRunEvent.AgentRunID = field.NewField(tableName, "agent_run_id")
	_agentRunEvent.Sequence = field.NewInt64(tableName, "sequence")
	_agentRunEvent.EventType = field.NewString(tableName, "event_type")
	_agentRunEvent.PayloadJSON = field.NewString(tableName, "payload_json")
	_agentRunEvent.CreatedAt = field.NewTime(tableName, "created_at")

	_agentRunEvent.fillFieldMap()

	return _agentRunEvent
}

type agentRunEvent struct {
	agentRunEventDo

	ALL         field.Asterisk
	ID          field.Field
	SessionID   field.Field
	AgentRunID  field.Field
	Sequence    field.Int64
	EventType   field.String
	PayloadJSON field.String
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (a agentRunEvent) Table(newTableName string) *agentRunEvent {
	a.agentRunEventDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentRunEvent) As(alias string) *agentRunEvent {
	a.agentRunEventDo.DO = *(a.agentRunEventDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentRunEvent) updateTableName(table string) *agentRunEvent {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewField(table, "id")
	a.SessionID = field.NewField(table, "session_id")
	a.AgentRunID = field.NewField(table, "agent_run_id")
	a.Sequence = field.NewInt64(table, "sequence")
	a.EventType = field.NewString(table, "event_type")
	a.PayloadJSON = field.NewString(table, "payload_json")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *agentRunEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentRunEvent) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 7)
	a.fieldMap["id"] = a.ID
	a.fieldMap["session_id"] = a.SessionID
	a.fieldMap["agent_run_id"] = a.AgentRunID
	a.fieldMap["sequence"] = a.Sequence
	a.fieldMap["event_type"] = a.EventType
	a.fieldMap["payload_json"] = a.PayloadJSON
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a agentRunEvent) clone(db *gorm.DB) agentRunEvent {
	a.agentRunEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentRunEvent) replaceDB(db *gorm.DB) agentRunEvent {
	a.agentRunEventDo.ReplaceDB(db)
	return a
}

type agentRunEventDo struct{ gen.DO }

type IAgentRunEventDo interface {
	gen.SubQuery
	Debug() IAgentRunEventDo
	WithContext(ctx context.Context) IAgentRunEventDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAgentRunEventDo
	WriteDB() IAgentRunEventDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAgentRunEventDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAgentRunEventDo
	Not(conds ...gen.Condition) IAgentRunEventDo
	Or(conds ...gen.Condition) IAgentRunEventDo
	Select(conds ...field.Expr) IAgentRunEventDo
	Where(conds ...gen.Condition) IAgentRunEventDo
	Order(conds ...field.Expr) IAgentRunEventDo
	Distinct(cols ...field.Expr) IAgentRunEventDo
	Omit(cols ...field.Expr) IAgentRunEventDo
	Join(table schema.Tabler, on ...field.Expr) IAgentRunEventDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAgentRunEventDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAgentRunEventDo
	Group(cols ...field.Expr) IAgentRunEventDo
	Having(conds ...gen.Condition) IAgentRunEventDo
	Limit(limit int) IAgentRunEventDo
	Offset(offset int) IAgentRunEventDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentRunEventDo
	Unscoped() IAgentRunEventDo
	Create(values ...*models.AgentRunEvent) error
	CreateInBatches(values []*models.AgentRunEvent, batchSize int) error
	Save(values ...*models.AgentRunEvent) error
	First() (*models.AgentRunEvent, error)
	Take() (*models.AgentRunEvent, error)
	Last() (*models.AgentRunEvent, error)
	Find() ([]*models.AgentRunEvent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentRunEvent, err error)
	FindInBatches(result *[]*models.AgentRunEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.AgentRunEvent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAgentRunEventDo
	Assign(attrs ...field.AssignExpr) IAgentRunEventDo
	Joins(fields ...field.RelationField) IAgentRunEventDo
	Preload(fields ...field.RelationField) IAgentRunEventDo
	FirstOrInit() (*models.AgentRunEvent, error)
	FirstOrCreate() (*models.AgentRunEvent, error)
	FindByPage(offset int, limit int) (result []*models.AgentRunEvent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAgentRunEventDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a agentRunEventDo) Debug() IAgentRunEventDo {
	return a.withDO(a.DO.Debug())
}

func (a agentRunEventDo) WithContext(ctx context.Context) IAgentRunEventDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a agentRunEventDo) ReadDB() IAgentRunEventDo {
	return a.Clauses(dbresolver.Read)
}

func (a agentRunEventDo) WriteDB() IAgentRunEventDo {
	return a.Clauses(dbresolver.Write)
}

func (a agentRunEventDo) Session(config *gorm.Session) IAgentRunEventDo {
	return a.withDO(a.DO.Session(config))
}

func (a agentRunEventDo) Clauses(conds ...clause.Expression) IAgentRunEventDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a agentRunEventDo) Returning(value interface{}, columns ...string) IAgentRunEventDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a agentRunEventDo) Not(conds ...gen.Condition) IAgentRunEventDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a agentRunEventDo) Or(conds ...gen.Condition) IAgentRunEventDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a agentRunEventDo) Select(conds ...field.Expr) IAgentRunEventDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a agentRunEventDo) Where(conds ...gen.Condition) IAgentRunEventDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a agentRunEventDo) Order(conds ...field.Expr) IAgentRunEventDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a agentRunEventDo) Distinct(cols ...field.Expr) IAgentRunEventDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a agentRunEventDo) Omit(cols ...field.Expr) IAgentRunEventDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a agentRunEventDo) Join(table schema.Tabler, on ...field.Expr) IAgentRunEventDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a agentRunEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAgentRunEventDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a agentRunEventDo) RightJoin(table schema.Tabler, on ...field.Expr) IAgentRunEventDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a agentRunEventDo) Group(cols ...field.Expr) IAgentRunEventDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a agentRunEventDo) Having(conds ...gen.Condition) IAgentRunEventDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a agentRunEventDo) Limit(limit int) IAgentRunEventDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a agentRunEventDo) Offset(offset int) IAgentRunEventDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a agentRunEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentRunEventDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a agentRunEventDo) Unscoped() IAgentRunEventDo {
	return a.withDO(a.DO.Unscoped())
}

func (a agentRunEventDo) Create(values ...*models.AgentRunEvent) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a agentRunEventDo) CreateInBatches(values []*models.AgentRunEvent, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a agentRunEventDo) Save(values ...*models.AgentRunEvent) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a agentRunEventDo) First() (*models.AgentRunEvent, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRunEvent), nil
	}
}

func (a agentRunEventDo) Take() (*models.AgentRunEvent, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRunEvent), nil
	}
}

func (a agentRunEventDo) Last() (*models.AgentRunEvent, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRunEvent), nil
	}
}

func (a agentRunEventDo) Find() ([]*models.AgentRunEvent, error) {
	result, err := a.DO.Find()
	return result.([]*models.AgentRunEvent), err
}

func (a agentRunEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentRunEvent, err error) {
	buf := make([]*models.AgentRunEvent, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a agentRunEventDo) FindInBatches(result *[]*models.AgentRunEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a agentRunEventDo) Attrs(attrs ...field.AssignExpr) IAgentRunEventDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a agentRunEventDo) Assign(attrs ...field.AssignExpr) IAgentRunEventDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a agentRunEventDo) Joins(fields ...field.RelationField) IAgentRunEventDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a agentRunEventDo) Preload(fields ...field.RelationField) IAgentRunEventDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a agentRunEventDo) FirstOrInit() (*models.AgentRunEvent, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRunEvent), nil
	}
}

func (a agentRunEventDo) FirstOrCreate() (*models.AgentRunEvent, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRunEvent), nil
	}
}

func (a agentRunEventDo) FindByPage(offset int, limit int) (result []*models.AgentRunEvent, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a agentRunEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a agentRunEventDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a agentRunEventDo) Delete(models ...*models.AgentRunEvent) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *agentRunEventDo) withDO(do gen.Dao) *agentRunEventDo {
	a.DO = *do.(*gen.DO)
	return a
}
