// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/peen/internal/pkg/db/models"

	"github.com/google/uuid"
)

func newCompaction(db *gorm.DB, opts ...gen.DOOption) compaction {
	_compaction := compaction{}

	_compaction.compactionDo.UseDB(db, opts...)
	_compaction.compactionDo.UseModel(&models.Compaction{})

	tableName := _compaction.compactionDo.TableName()
	_compaction.ALL = field.NewAsterisk(tableName)
	_compaction.ID = field.NewField(tableName, "id")
	_compaction.SessionID = field.NewField(tableName, "session_id")
	_compaction.FromMessageID = field.NewField(tableName, "from_message_id")
	_compaction.ToMessageID = field.NewField(tableName, "to_message_id")
	_compaction.FromSequence = field.NewInt64(tableName, "from_sequence")
	_compaction.ToSequence = field.NewInt64(tableName, "to_sequence")
	_compaction.Summary = field.NewString(tableName, "summary")
	_compaction.SourceMessageCount = field.NewInt64(tableName, "source_message_count")
	_compaction.InputTokenCount = field.NewInt64(tableName, "input_token_count")
	_compaction.SummaryTokenCount = field.NewInt64(tableName, "summary_token_count")
	_compaction.ModelID = field.NewString(tableName, "model_id")
	_compaction.PromptHash = field.NewString(tableName, "prompt_hash")
	_compaction.CreatedAt = field.NewTime(tableName, "created_at")
	_compaction.SupersedesCompactionID = field.NewField(tableName, "supersedes_compaction_id")

	_compaction.fillFieldMap()

	return _compaction
}

type compaction struct {
	compactionDo

	ALL                    field.Asterisk
	ID                     field.Field
	SessionID              field.Field
	FromMessageID          field.Field
	ToMessageID            field.Field
	FromSequence           field.Int64
	ToSequence             field.Int64
	Summary                field.String
	SourceMessageCount     field.Int64
	InputTokenCount        field.Int64
	SummaryTokenCount      field.Int64
	ModelID                field.String
	PromptHash             field.String
	CreatedAt              field.Time
	SupersedesCompactionID field.Field

	fieldMap map[string]field.Expr
}

func (c compaction) Table(newTableName string) *compaction {
	c.compactionDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c compaction) As(alias string) *compaction {
	c.compactionDo.DO = *(c.compactionDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *compaction) updateTableName(table string) *compaction {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewField(table, "id")
	c.SessionID = field.NewField(table, "session_id")
	c.FromMessageID = field.NewField(table, "from_message_id")
	c.ToMessageID = field.NewField(table, "to_message_id")
	c.FromSequence = field.NewInt64(table, "from_sequence")
	c.ToSequence = field.NewInt64(table, "to_sequence")
	c.Summary = field.NewString(table, "summary")
	c.SourceMessageCount = field.NewInt64(table, "source_message_count")
	c.InputTokenCount = field.NewInt64(table, "input_token_count")
	c.SummaryTokenCount = field.NewInt64(table, "summary_token_count")
	c.ModelID = field.NewString(table, "model_id")
	c.PromptHash = field.NewString(table, "prompt_hash")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.SupersedesCompactionID = field.NewField(table, "supersedes_compaction_id")

	c.fillFieldMap()

	return c
}

func (c *compaction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *compaction) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 14)
	c.fieldMap["id"] = c.ID
	c.fieldMap["session_id"] = c.SessionID
	c.fieldMap["from_message_id"] = c.FromMessageID
	c.fieldMap["to_message_id"] = c.ToMessageID
	c.fieldMap["from_sequence"] = c.FromSequence
	c.fieldMap["to_sequence"] = c.ToSequence
	c.fieldMap["summary"] = c.Summary
	c.fieldMap["source_message_count"] = c.SourceMessageCount
	c.fieldMap["input_token_count"] = c.InputTokenCount
	c.fieldMap["summary_token_count"] = c.SummaryTokenCount
	c.fieldMap["model_id"] = c.ModelID
	c.fieldMap["prompt_hash"] = c.PromptHash
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["supersedes_compaction_id"] = c.SupersedesCompactionID
}

func (c compaction) clone(db *gorm.DB) compaction {
	c.compactionDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c compaction) replaceDB(db *gorm.DB) compaction {
	c.compactionDo.ReplaceDB(db)
	return c
}

type compactionDo struct{ gen.DO }

type ICompactionDo interface {
	gen.SubQuery
	Debug() ICompactionDo
	WithContext(ctx context.Context) ICompactionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICompactionDo
	WriteDB() ICompactionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICompactionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICompactionDo
	Not(conds ...gen.Condition) ICompactionDo
	Or(conds ...gen.Condition) ICompactionDo
	Select(conds ...field.Expr) ICompactionDo
	Where(conds ...gen.Condition) ICompactionDo
	Order(conds ...field.Expr) ICompactionDo
	Distinct(cols ...field.Expr) ICompactionDo
	Omit(cols ...field.Expr) ICompactionDo
	Join(table schema.Tabler, on ...field.Expr) ICompactionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICompactionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICompactionDo
	Group(cols ...field.Expr) ICompactionDo
	Having(conds ...gen.Condition) ICompactionDo
	Limit(limit int) ICompactionDo
	Offset(offset int) ICompactionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICompactionDo
	Unscoped() ICompactionDo
	Create(values ...*models.Compaction) error
	CreateInBatches(values []*models.Compaction, batchSize int) error
	Save(values ...*models.Compaction) error
	First() (*models.Compaction, error)
	Take() (*models.Compaction, error)
	Last() (*models.Compaction, error)
	Find() ([]*models.Compaction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Compaction, err error)
	FindInBatches(result *[]*models.Compaction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Compaction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICompactionDo
	Assign(attrs ...field.AssignExpr) ICompactionDo
	Joins(fields ...field.RelationField) ICompactionDo
	Preload(fields ...field.RelationField) ICompactionDo
	FirstOrInit() (*models.Compaction, error)
	FirstOrCreate() (*models.Compaction, error)
	FindByPage(offset int, limit int) (result []*models.Compaction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICompactionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	ActiveHead(sessionID uuid.UUID) (result *models.Compaction, err error)
}

// SELECT current.*
//
//	FROM compactions AS current
//	WHERE current.session_id = @sessionID
//	  AND NOT EXISTS (
//		  SELECT 1
//		  FROM compactions AS newer
//		  WHERE newer.session_id = current.session_id
//		    AND newer.supersedes_compaction_id = current.id
//	  )
//	ORDER BY current.to_sequence DESC, current.id DESC
//	LIMIT 1
func (c compactionDo) ActiveHead(sessionID uuid.UUID) (result *models.Compaction, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	generateSQL.WriteString("SELECT current.* FROM compactions AS current WHERE current.session_id = ? AND NOT EXISTS ( SELECT 1 FROM compactions AS newer WHERE newer.session_id = current.session_id AND newer.supersedes_compaction_id = current.id ) ORDER BY current.to_sequence DESC, current.id DESC LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (c compactionDo) Debug() ICompactionDo {
	return c.withDO(c.DO.Debug())
}

func (c compactionDo) WithContext(ctx context.Context) ICompactionDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c compactionDo) ReadDB() ICompactionDo {
	return c.Clauses(dbresolver.Read)
}

func (c compactionDo) WriteDB() ICompactionDo {
	return c.Clauses(dbresolver.Write)
}

func (c compactionDo) Session(config *gorm.Session) ICompactionDo {
	return c.withDO(c.DO.Session(config))
}

func (c compactionDo) Clauses(conds ...clause.Expression) ICompactionDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c compactionDo) Returning(value interface{}, columns ...string) ICompactionDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c compactionDo) Not(conds ...gen.Condition) ICompactionDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c compactionDo) Or(conds ...gen.Condition) ICompactionDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c compactionDo) Select(conds ...field.Expr) ICompactionDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c compactionDo) Where(conds ...gen.Condition) ICompactionDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c compactionDo) Order(conds ...field.Expr) ICompactionDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c compactionDo) Distinct(cols ...field.Expr) ICompactionDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c compactionDo) Omit(cols ...field.Expr) ICompactionDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c compactionDo) Join(table schema.Tabler, on ...field.Expr) ICompactionDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c compactionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICompactionDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c compactionDo) RightJoin(table schema.Tabler, on ...field.Expr) ICompactionDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c compactionDo) Group(cols ...field.Expr) ICompactionDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c compactionDo) Having(conds ...gen.Condition) ICompactionDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c compactionDo) Limit(limit int) ICompactionDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c compactionDo) Offset(offset int) ICompactionDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c compactionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICompactionDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c compactionDo) Unscoped() ICompactionDo {
	return c.withDO(c.DO.Unscoped())
}

func (c compactionDo) Create(values ...*models.Compaction) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c compactionDo) CreateInBatches(values []*models.Compaction, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c compactionDo) Save(values ...*models.Compaction) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c compactionDo) First() (*models.Compaction, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Compaction), nil
	}
}

func (c compactionDo) Take() (*models.Compaction, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Compaction), nil
	}
}

func (c compactionDo) Last() (*models.Compaction, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Compaction), nil
	}
}

func (c compactionDo) Find() ([]*models.Compaction, error) {
	result, err := c.DO.Find()
	return result.([]*models.Compaction), err
}

func (c compactionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Compaction, err error) {
	buf := make([]*models.Compaction, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c compactionDo) FindInBatches(result *[]*models.Compaction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c compactionDo) Attrs(attrs ...field.AssignExpr) ICompactionDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c compactionDo) Assign(attrs ...field.AssignExpr) ICompactionDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c compactionDo) Joins(fields ...field.RelationField) ICompactionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c compactionDo) Preload(fields ...field.RelationField) ICompactionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c compactionDo) FirstOrInit() (*models.Compaction, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Compaction), nil
	}
}

func (c compactionDo) FirstOrCreate() (*models.Compaction, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Compaction), nil
	}
}

func (c compactionDo) FindByPage(offset int, limit int) (result []*models.Compaction, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c compactionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c compactionDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c compactionDo) Delete(models ...*models.Compaction) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *compactionDo) withDO(do gen.Dao) *compactionDo {
	c.DO = *do.(*gen.DO)
	return c
}
