// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/peen/internal/pkg/db/models"
)

func newContextSnapshot(db *gorm.DB, opts ...gen.DOOption) contextSnapshot {
	_contextSnapshot := contextSnapshot{}

	_contextSnapshot.contextSnapshotDo.UseDB(db, opts...)
	_contextSnapshot.contextSnapshotDo.UseModel(&models.ContextSnapshot{})

	tableName := _contextSnapshot.contextSnapshotDo.TableName()
	_contextSnapshot.ALL = field.NewAsterisk(tableName)
	_contextSnapshot.Hash = field.NewString(tableName, "hash")
	_contextSnapshot.ManifestJSON = field.NewString(tableName, "manifest_json")
	_contextSnapshot.ResolvedContent = field.NewString(tableName, "resolved_content")
	_contextSnapshot.CreatedAt = field.NewTime(tableName, "created_at")

	_contextSnapshot.fillFieldMap()

	return _contextSnapshot
}

type contextSnapshot struct {
	contextSnapshotDo

	ALL             field.Asterisk
	Hash            field.String
	ManifestJSON    field.String
	ResolvedContent field.String
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (c contextSnapshot) Table(newTableName string) *contextSnapshot {
	c.contextSnapshotDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c contextSnapshot) As(alias string) *contextSnapshot {
	c.contextSnapshotDo.DO = *(c.contextSnapshotDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *contextSnapshot) updateTableName(table string) *contextSnapshot {
	c.ALL = field.NewAsterisk(table)
	c.Hash = field.NewString(table, "hash")
	c.ManifestJSON = field.NewString(table, "manifest_json")
	c.ResolvedContent = field.NewString(table, "resolved_content")
	c.CreatedAt = field.NewTime(table, "created_at")

	c.fillFieldMap()

	return c
}

func (c *contextSnapshot) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *contextSnapshot) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 4)
	c.fieldMap["hash"] = c.Hash
	c.fieldMap["manifest_json"] = c.ManifestJSON
	c.fieldMap["resolved_content"] = c.ResolvedContent
	c.fieldMap["created_at"] = c.CreatedAt
}

func (c contextSnapshot) clone(db *gorm.DB) contextSnapshot {
	c.contextSnapshotDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c contextSnapshot) replaceDB(db *gorm.DB) contextSnapshot {
	c.contextSnapshotDo.ReplaceDB(db)
	return c
}

type contextSnapshotDo struct{ gen.DO }

type IContextSnapshotDo interface {
	gen.SubQuery
	Debug() IContextSnapshotDo
	WithContext(ctx context.Context) IContextSnapshotDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IContextSnapshotDo
	WriteDB() IContextSnapshotDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IContextSnapshotDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IContextSnapshotDo
	Not(conds ...gen.Condition) IContextSnapshotDo
	Or(conds ...gen.Condition) IContextSnapshotDo
	Select(conds ...field.Expr) IContextSnapshotDo
	Where(conds ...gen.Condition) IContextSnapshotDo
	Order(conds ...field.Expr) IContextSnapshotDo
	Distinct(cols ...field.Expr) IContextSnapshotDo
	Omit(cols ...field.Expr) IContextSnapshotDo
	Join(table schema.Tabler, on ...field.Expr) IContextSnapshotDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IContextSnapshotDo
	RightJoin(table schema.Tabler, on ...field.Expr) IContextSnapshotDo
	Group(cols ...field.Expr) IContextSnapshotDo
	Having(conds ...gen.Condition) IContextSnapshotDo
	Limit(limit int) IContextSnapshotDo
	Offset(offset int) IContextSnapshotDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IContextSnapshotDo
	Unscoped() IContextSnapshotDo
	Create(values ...*models.ContextSnapshot) error
	CreateInBatches(values []*models.ContextSnapshot, batchSize int) error
	Save(values ...*models.ContextSnapshot) error
	First() (*models.ContextSnapshot, error)
	Take() (*models.ContextSnapshot, error)
	Last() (*models.ContextSnapshot, error)
	Find() ([]*models.ContextSnapshot, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ContextSnapshot, err error)
	FindInBatches(result *[]*models.ContextSnapshot, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ContextSnapshot) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IContextSnapshotDo
	Assign(attrs ...field.AssignExpr) IContextSnapshotDo
	Joins(fields ...field.RelationField) IContextSnapshotDo
	Preload(fields ...field.RelationField) IContextSnapshotDo
	FirstOrInit() (*models.ContextSnapshot, error)
	FirstOrCreate() (*models.ContextSnapshot, error)
	FindByPage(offset int, limit int) (result []*models.ContextSnapshot, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IContextSnapshotDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c contextSnapshotDo) Debug() IContextSnapshotDo {
	return c.withDO(c.DO.Debug())
}

func (c contextSnapshotDo) WithContext(ctx context.Context) IContextSnapshotDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c contextSnapshotDo) ReadDB() IContextSnapshotDo {
	return c.Clauses(dbresolver.Read)
}

func (c contextSnapshotDo) WriteDB() IContextSnapshotDo {
	return c.Clauses(dbresolver.Write)
}

func (c contextSnapshotDo) Session(config *gorm.Session) IContextSnapshotDo {
	return c.withDO(c.DO.Session(config))
}

func (c contextSnapshotDo) Clauses(conds ...clause.Expression) IContextSnapshotDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c contextSnapshotDo) Returning(value interface{}, columns ...string) IContextSnapshotDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c contextSnapshotDo) Not(conds ...gen.Condition) IContextSnapshotDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c contextSnapshotDo) Or(conds ...gen.Condition) IContextSnapshotDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c contextSnapshotDo) Select(conds ...field.Expr) IContextSnapshotDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c contextSnapshotDo) Where(conds ...gen.Condition) IContextSnapshotDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c contextSnapshotDo) Order(conds ...field.Expr) IContextSnapshotDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c contextSnapshotDo) Distinct(cols ...field.Expr) IContextSnapshotDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c contextSnapshotDo) Omit(cols ...field.Expr) IContextSnapshotDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c contextSnapshotDo) Join(table schema.Tabler, on ...field.Expr) IContextSnapshotDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c contextSnapshotDo) LeftJoin(table schema.Tabler, on ...field.Expr) IContextSnapshotDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c contextSnapshotDo) RightJoin(table schema.Tabler, on ...field.Expr) IContextSnapshotDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c contextSnapshotDo) Group(cols ...field.Expr) IContextSnapshotDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c contextSnapshotDo) Having(conds ...gen.Condition) IContextSnapshotDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c contextSnapshotDo) Limit(limit int) IContextSnapshotDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c contextSnapshotDo) Offset(offset int) IContextSnapshotDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c contextSnapshotDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IContextSnapshotDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c contextSnapshotDo) Unscoped() IContextSnapshotDo {
	return c.withDO(c.DO.Unscoped())
}

func (c contextSnapshotDo) Create(values ...*models.ContextSnapshot) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c contextSnapshotDo) CreateInBatches(values []*models.ContextSnapshot, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c contextSnapshotDo) Save(values ...*models.ContextSnapshot) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c contextSnapshotDo) First() (*models.ContextSnapshot, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ContextSnapshot), nil
	}
}

func (c contextSnapshotDo) Take() (*models.ContextSnapshot, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ContextSnapshot), nil
	}
}

func (c contextSnapshotDo) Last() (*models.ContextSnapshot, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ContextSnapshot), nil
	}
}

func (c contextSnapshotDo) Find() ([]*models.ContextSnapshot, error) {
	result, err := c.DO.Find()
	return result.([]*models.ContextSnapshot), err
}

func (c contextSnapshotDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ContextSnapshot, err error) {
	buf := make([]*models.ContextSnapshot, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c contextSnapshotDo) FindInBatches(result *[]*models.ContextSnapshot, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c contextSnapshotDo) Attrs(attrs ...field.AssignExpr) IContextSnapshotDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c contextSnapshotDo) Assign(attrs ...field.AssignExpr) IContextSnapshotDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c contextSnapshotDo) Joins(fields ...field.RelationField) IContextSnapshotDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c contextSnapshotDo) Preload(fields ...field.RelationField) IContextSnapshotDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c contextSnapshotDo) FirstOrInit() (*models.ContextSnapshot, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ContextSnapshot), nil
	}
}

func (c contextSnapshotDo) FirstOrCreate() (*models.ContextSnapshot, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ContextSnapshot), nil
	}
}

func (c contextSnapshotDo) FindByPage(offset int, limit int) (result []*models.ContextSnapshot, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c contextSnapshotDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c contextSnapshotDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c contextSnapshotDo) Delete(models ...*models.ContextSnapshot) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *contextSnapshotDo) withDO(do gen.Dao) *contextSnapshotDo {
	c.DO = *do.(*gen.DO)
	return c
}
