// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/peen/internal/pkg/db/models"
)

func newJobOutputLine(db *gorm.DB, opts ...gen.DOOption) jobOutputLine {
	_jobOutputLine := jobOutputLine{}

	_jobOutputLine.jobOutputLineDo.UseDB(db, opts...)
	_jobOutputLine.jobOutputLineDo.UseModel(&models.JobOutputLine{})

	tableName := _jobOutputLine.jobOutputLineDo.TableName()
	_jobOutputLine.ALL = field.NewAsterisk(tableName)
	_jobOutputLine.ID = field.NewField(tableName, "id")
	_jobOutputLine.SessionID = field.NewField(tableName, "session_id")
	_jobOutputLine.JobID = field.NewField(tableName, "job_id")
	_jobOutputLine.Sequence = field.NewInt64(tableName, "sequence")
	_jobOutputLine.Stream = field.NewString(tableName, "stream")
	_jobOutputLine.Content = field.NewString(tableName, "content")
	_jobOutputLine.CreatedAt = field.NewTime(tableName, "created_at")

	_jobOutputLine.fillFieldMap()

	return _jobOutputLine
}

type jobOutputLine struct {
	jobOutputLineDo

	ALL       field.Asterisk
	ID        field.Field
	SessionID field.Field
	JobID     field.Field
	Sequence  field.Int64
	Stream    field.String
	Content   field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (j jobOutputLine) Table(newTableName string) *jobOutputLine {
	j.jobOutputLineDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobOutputLine) As(alias string) *jobOutputLine {
	j.jobOutputLineDo.DO = *(j.jobOutputLineDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobOutputLine) updateTableName(table string) *jobOutputLine {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewField(table, "id")
	j.SessionID = field.NewField(table, "session_id")
	j.JobID = field.NewField(table, "job_id")
	j.Sequence = field.NewInt64(table, "sequence")
	j.Stream = field.NewString(table, "stream")
	j.Content = field.NewString(table, "content")
	j.CreatedAt = field.NewTime(table, "created_at")

	j.fillFieldMap()

	return j
}

func (j *jobOutputLine) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobOutputLine) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 7)
	j.fieldMap["id"] = j.ID
	j.fieldMap["session_id"] = j.SessionID
	j.fieldMap["job_id"] = j.JobID
	j.fieldMap["sequence"] = j.Sequence
	j.fieldMap["stream"] = j.Stream
	j.fieldMap["content"] = j.Content
	j.fieldMap["created_at"] = j.CreatedAt
}

func (j jobOutputLine) clone(db *gorm.DB) jobOutputLine {
	j.jobOutputLineDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobOutputLine) replaceDB(db *gorm.DB) jobOutputLine {
	j.jobOutputLineDo.ReplaceDB(db)
	return j
}

type jobOutputLineDo struct{ gen.DO }

type IJobOutputLineDo interface {
	gen.SubQuery
	Debug() IJobOutputLineDo
	WithContext(ctx context.Context) IJobOutputLineDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobOutputLineDo
	WriteDB() IJobOutputLineDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobOutputLineDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobOutputLineDo
	Not(conds ...gen.Condition) IJobOutputLineDo
	Or(conds ...gen.Condition) IJobOutputLineDo
	Select(conds ...field.Expr) IJobOutputLineDo
	Where(conds ...gen.Condition) IJobOutputLineDo
	Order(conds ...field.Expr) IJobOutputLineDo
	Distinct(cols ...field.Expr) IJobOutputLineDo
	Omit(cols ...field.Expr) IJobOutputLineDo
	Join(table schema.Tabler, on ...field.Expr) IJobOutputLineDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobOutputLineDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobOutputLineDo
	Group(cols ...field.Expr) IJobOutputLineDo
	Having(conds ...gen.Condition) IJobOutputLineDo
	Limit(limit int) IJobOutputLineDo
	Offset(offset int) IJobOutputLineDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobOutputLineDo
	Unscoped() IJobOutputLineDo
	Create(values ...*models.JobOutputLine) error
	CreateInBatches(values []*models.JobOutputLine, batchSize int) error
	Save(values ...*models.JobOutputLine) error
	First() (*models.JobOutputLine, error)
	Take() (*models.JobOutputLine, error)
	Last() (*models.JobOutputLine, error)
	Find() ([]*models.JobOutputLine, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobOutputLine, err error)
	FindInBatches(result *[]*models.JobOutputLine, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.JobOutputLine) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobOutputLineDo
	Assign(attrs ...field.AssignExpr) IJobOutputLineDo
	Joins(fields ...field.RelationField) IJobOutputLineDo
	Preload(fields ...field.RelationField) IJobOutputLineDo
	FirstOrInit() (*models.JobOutputLine, error)
	FirstOrCreate() (*models.JobOutputLine, error)
	FindByPage(offset int, limit int) (result []*models.JobOutputLine, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobOutputLineDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobOutputLineDo) Debug() IJobOutputLineDo {
	return j.withDO(j.DO.Debug())
}

func (j jobOutputLineDo) WithContext(ctx context.Context) IJobOutputLineDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobOutputLineDo) ReadDB() IJobOutputLineDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobOutputLineDo) WriteDB() IJobOutputLineDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobOutputLineDo) Session(config *gorm.Session) IJobOutputLineDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobOutputLineDo) Clauses(conds ...clause.Expression) IJobOutputLineDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobOutputLineDo) Returning(value interface{}, columns ...string) IJobOutputLineDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobOutputLineDo) Not(conds ...gen.Condition) IJobOutputLineDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobOutputLineDo) Or(conds ...gen.Condition) IJobOutputLineDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobOutputLineDo) Select(conds ...field.Expr) IJobOutputLineDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobOutputLineDo) Where(conds ...gen.Condition) IJobOutputLineDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobOutputLineDo) Order(conds ...field.Expr) IJobOutputLineDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobOutputLineDo) Distinct(cols ...field.Expr) IJobOutputLineDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobOutputLineDo) Omit(cols ...field.Expr) IJobOutputLineDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobOutputLineDo) Join(table schema.Tabler, on ...field.Expr) IJobOutputLineDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobOutputLineDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobOutputLineDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobOutputLineDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobOutputLineDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobOutputLineDo) Group(cols ...field.Expr) IJobOutputLineDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobOutputLineDo) Having(conds ...gen.Condition) IJobOutputLineDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobOutputLineDo) Limit(limit int) IJobOutputLineDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobOutputLineDo) Offset(offset int) IJobOutputLineDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobOutputLineDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobOutputLineDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobOutputLineDo) Unscoped() IJobOutputLineDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobOutputLineDo) Create(values ...*models.JobOutputLine) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobOutputLineDo) CreateInBatches(values []*models.JobOutputLine, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobOutputLineDo) Save(values ...*models.JobOutputLine) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobOutputLineDo) First() (*models.JobOutputLine, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobOutputLine), nil
	}
}

func (j jobOutputLineDo) Take() (*models.JobOutputLine, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobOutputLine), nil
	}
}

func (j jobOutputLineDo) Last() (*models.JobOutputLine, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobOutputLine), nil
	}
}

func (j jobOutputLineDo) Find() ([]*models.JobOutputLine, error) {
	result, err := j.DO.Find()
	return result.([]*models.JobOutputLine), err
}

func (j jobOutputLineDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobOutputLine, err error) {
	buf := make([]*models.JobOutputLine, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobOutputLineDo) FindInBatches(result *[]*models.JobOutputLine, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobOutputLineDo) Attrs(attrs ...field.AssignExpr) IJobOutputLineDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobOutputLineDo) Assign(attrs ...field.AssignExpr) IJobOutputLineDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobOutputLineDo) Joins(fields ...field.RelationField) IJobOutputLineDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobOutputLineDo) Preload(fields ...field.RelationField) IJobOutputLineDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobOutputLineDo) FirstOrInit() (*models.JobOutputLine, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobOutputLine), nil
	}
}

func (j jobOutputLineDo) FirstOrCreate() (*models.JobOutputLine, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobOutputLine), nil
	}
}

func (j jobOutputLineDo) FindByPage(offset int, limit int) (result []*models.JobOutputLine, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobOutputLineDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobOutputLineDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobOutputLineDo) Delete(models ...*models.JobOutputLine) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobOutputLineDo) withDO(do gen.Dao) *jobOutputLineDo {
	j.DO = *do.(*gen.DO)
	return j
}
