// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/peen/internal/pkg/db/models"
)

func newJobSignalRequest(db *gorm.DB, opts ...gen.DOOption) jobSignalRequest {
	_jobSignalRequest := jobSignalRequest{}

	_jobSignalRequest.jobSignalRequestDo.UseDB(db, opts...)
	_jobSignalRequest.jobSignalRequestDo.UseModel(&models.JobSignalRequest{})

	tableName := _jobSignalRequest.jobSignalRequestDo.TableName()
	_jobSignalRequest.ALL = field.NewAsterisk(tableName)
	_jobSignalRequest.ID = field.NewField(tableName, "id")
	_jobSignalRequest.SessionID = field.NewField(tableName, "session_id")
	_jobSignalRequest.JobID = field.NewField(tableName, "job_id")
	_jobSignalRequest.Signal = field.NewString(tableName, "signal")
	_jobSignalRequest.Accepted = field.NewBool(tableName, "accepted")
	_jobSignalRequest.StateAtRequest = field.NewString(tableName, "state_at_request")
	_jobSignalRequest.RequestedAt = field.NewTime(tableName, "requested_at")

	_jobSignalRequest.fillFieldMap()

	return _jobSignalRequest
}

type jobSignalRequest struct {
	jobSignalRequestDo

	ALL            field.Asterisk
	ID             field.Field
	SessionID      field.Field
	JobID          field.Field
	Signal         field.String
	Accepted       field.Bool
	StateAtRequest field.String
	RequestedAt    field.Time

	fieldMap map[string]field.Expr
}

func (j jobSignalRequest) Table(newTableName string) *jobSignalRequest {
	j.jobSignalRequestDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobSignalRequest) As(alias string) *jobSignalRequest {
	j.jobSignalRequestDo.DO = *(j.jobSignalRequestDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobSignalRequest) updateTableName(table string) *jobSignalRequest {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewField(table, "id")
	j.SessionID = field.NewField(table, "session_id")
	j.JobID = field.NewField(table, "job_id")
	j.Signal = field.NewString(table, "signal")
	j.Accepted = field.NewBool(table, "accepted")
	j.StateAtRequest = field.NewString(table, "state_at_request")
	j.RequestedAt = field.NewTime(table, "requested_at")

	j.fillFieldMap()

	return j
}

func (j *jobSignalRequest) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobSignalRequest) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 7)
	j.fieldMap["id"] = j.ID
	j.fieldMap["session_id"] = j.SessionID
	j.fieldMap["job_id"] = j.JobID
	j.fieldMap["signal"] = j.Signal
	j.fieldMap["accepted"] = j.Accepted
	j.fieldMap["state_at_request"] = j.StateAtRequest
	j.fieldMap["requested_at"] = j.RequestedAt
}

func (j jobSignalRequest) clone(db *gorm.DB) jobSignalRequest {
	j.jobSignalRequestDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobSignalRequest) replaceDB(db *gorm.DB) jobSignalRequest {
	j.jobSignalRequestDo.ReplaceDB(db)
	return j
}

type jobSignalRequestDo struct{ gen.DO }

type IJobSignalRequestDo interface {
	gen.SubQuery
	Debug() IJobSignalRequestDo
	WithContext(ctx context.Context) IJobSignalRequestDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobSignalRequestDo
	WriteDB() IJobSignalRequestDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobSignalRequestDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobSignalRequestDo
	Not(conds ...gen.Condition) IJobSignalRequestDo
	Or(conds ...gen.Condition) IJobSignalRequestDo
	Select(conds ...field.Expr) IJobSignalRequestDo
	Where(conds ...gen.Condition) IJobSignalRequestDo
	Order(conds ...field.Expr) IJobSignalRequestDo
	Distinct(cols ...field.Expr) IJobSignalRequestDo
	Omit(cols ...field.Expr) IJobSignalRequestDo
	Join(table schema.Tabler, on ...field.Expr) IJobSignalRequestDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobSignalRequestDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobSignalRequestDo
	Group(cols ...field.Expr) IJobSignalRequestDo
	Having(conds ...gen.Condition) IJobSignalRequestDo
	Limit(limit int) IJobSignalRequestDo
	Offset(offset int) IJobSignalRequestDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobSignalRequestDo
	Unscoped() IJobSignalRequestDo
	Create(values ...*models.JobSignalRequest) error
	CreateInBatches(values []*models.JobSignalRequest, batchSize int) error
	Save(values ...*models.JobSignalRequest) error
	First() (*models.JobSignalRequest, error)
	Take() (*models.JobSignalRequest, error)
	Last() (*models.JobSignalRequest, error)
	Find() ([]*models.JobSignalRequest, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobSignalRequest, err error)
	FindInBatches(result *[]*models.JobSignalRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.JobSignalRequest) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobSignalRequestDo
	Assign(attrs ...field.AssignExpr) IJobSignalRequestDo
	Joins(fields ...field.RelationField) IJobSignalRequestDo
	Preload(fields ...field.RelationField) IJobSignalRequestDo
	FirstOrInit() (*models.JobSignalRequest, error)
	FirstOrCreate() (*models.JobSignalRequest, error)
	FindByPage(offset int, limit int) (result []*models.JobSignalRequest, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobSignalRequestDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobSignalRequestDo) Debug() IJobSignalRequestDo {
	return j.withDO(j.DO.Debug())
}

func (j jobSignalRequestDo) WithContext(ctx context.Context) IJobSignalRequestDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobSignalRequestDo) ReadDB() IJobSignalRequestDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobSignalRequestDo) WriteDB() IJobSignalRequestDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobSignalRequestDo) Session(config *gorm.Session) IJobSignalRequestDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobSignalRequestDo) Clauses(conds ...clause.Expression) IJobSignalRequestDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobSignalRequestDo) Returning(value interface{}, columns ...string) IJobSignalRequestDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobSignalRequestDo) Not(conds ...gen.Condition) IJobSignalRequestDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobSignalRequestDo) Or(conds ...gen.Condition) IJobSignalRequestDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobSignalRequestDo) Select(conds ...field.Expr) IJobSignalRequestDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobSignalRequestDo) Where(conds ...gen.Condition) IJobSignalRequestDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobSignalRequestDo) Order(conds ...field.Expr) IJobSignalRequestDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobSignalRequestDo) Distinct(cols ...field.Expr) IJobSignalRequestDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobSignalRequestDo) Omit(cols ...field.Expr) IJobSignalRequestDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobSignalRequestDo) Join(table schema.Tabler, on ...field.Expr) IJobSignalRequestDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobSignalRequestDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobSignalRequestDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobSignalRequestDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobSignalRequestDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobSignalRequestDo) Group(cols ...field.Expr) IJobSignalRequestDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobSignalRequestDo) Having(conds ...gen.Condition) IJobSignalRequestDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobSignalRequestDo) Limit(limit int) IJobSignalRequestDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobSignalRequestDo) Offset(offset int) IJobSignalRequestDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobSignalRequestDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobSignalRequestDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobSignalRequestDo) Unscoped() IJobSignalRequestDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobSignalRequestDo) Create(values ...*models.JobSignalRequest) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobSignalRequestDo) CreateInBatches(values []*models.JobSignalRequest, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobSignalRequestDo) Save(values ...*models.JobSignalRequest) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobSignalRequestDo) First() (*models.JobSignalRequest, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobSignalRequest), nil
	}
}

func (j jobSignalRequestDo) Take() (*models.JobSignalRequest, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobSignalRequest), nil
	}
}

func (j jobSignalRequestDo) Last() (*models.JobSignalRequest, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobSignalRequest), nil
	}
}

func (j jobSignalRequestDo) Find() ([]*models.JobSignalRequest, error) {
	result, err := j.DO.Find()
	return result.([]*models.JobSignalRequest), err
}

func (j jobSignalRequestDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobSignalRequest, err error) {
	buf := make([]*models.JobSignalRequest, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobSignalRequestDo) FindInBatches(result *[]*models.JobSignalRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobSignalRequestDo) Attrs(attrs ...field.AssignExpr) IJobSignalRequestDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobSignalRequestDo) Assign(attrs ...field.AssignExpr) IJobSignalRequestDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobSignalRequestDo) Joins(fields ...field.RelationField) IJobSignalRequestDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobSignalRequestDo) Preload(fields ...field.RelationField) IJobSignalRequestDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobSignalRequestDo) FirstOrInit() (*models.JobSignalRequest, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobSignalRequest), nil
	}
}

func (j jobSignalRequestDo) FirstOrCreate() (*models.JobSignalRequest, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobSignalRequest), nil
	}
}

func (j jobSignalRequestDo) FindByPage(offset int, limit int) (result []*models.JobSignalRequest, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobSignalRequestDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobSignalRequestDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobSignalRequestDo) Delete(models ...*models.JobSignalRequest) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobSignalRequestDo) withDO(do gen.Dao) *jobSignalRequestDo {
	j.DO = *do.(*gen.DO)
	return j
}
