// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/peen/internal/pkg/db/models"
)

func newModelCall(db *gorm.DB, opts ...gen.DOOption) modelCall {
	_modelCall := modelCall{}

	_modelCall.modelCallDo.UseDB(db, opts...)
	_modelCall.modelCallDo.UseModel(&models.ModelCall{})

	tableName := _modelCall.modelCallDo.TableName()
	_modelCall.ALL = field.NewAsterisk(tableName)
	_modelCall.ID = field.NewField(tableName, "id")
	_modelCall.SessionID = field.NewField(tableName, "session_id")
	_modelCall.ModelRunID = field.NewField(tableName, "model_run_id")
	_modelCall.Round = field.NewInt64(tableName, "round")
	_modelCall.RequestMessagesJSON = field.NewString(tableName, "request_messages_json")
	_modelCall.RequestToolsJSON = field.NewString(tableName, "request_tools_json")
	_modelCall.State = field.NewString(tableName, "state")
	_modelCall.ResponseMessageJSON = field.NewString(tableName, "response_message_json")
	_modelCall.ResponseUsageJSON = field.NewString(tableName, "response_usage_json")
	_modelCall.RetryAttemptsJSON = field.NewString(tableName, "retry_attempts_json")
	_modelCall.RetryAttemptCount = field.NewInt64(tableName, "retry_attempt_count")
	_modelCall.PromptTokens = field.NewInt64(tableName, "prompt_tokens")
	_modelCall.CompletionTokens = field.NewInt64(tableName, "completion_tokens")
	_modelCall.TotalTokens = field.NewInt64(tableName, "total_tokens")
	_modelCall.ReasoningTokens = field.NewInt64(tableName, "reasoning_tokens")
	_modelCall.CacheReadTokens = field.NewInt64(tableName, "cache_read_tokens")
	_modelCall.CacheWriteTokens = field.NewInt64(tableName, "cache_write_tokens")
	_modelCall.CacheWriteLongTTLTokens = field.NewInt64(tableName, "cache_write_long_ttl_tokens")
	_modelCall.WastedPromptTokens = field.NewInt64(tableName, "wasted_prompt_tokens")
	_modelCall.WastedCompletionTokens = field.NewInt64(tableName, "wasted_completion_tokens")
	_modelCall.WastedTotalTokens = field.NewInt64(tableName, "wasted_total_tokens")
	_modelCall.TotalAttempts = field.NewInt64(tableName, "total_attempts")
	_modelCall.ResponseModelID = field.NewString(tableName, "response_model_id")
	_modelCall.FinishReason = field.NewString(tableName, "finish_reason")
	_modelCall.ResponseCostAmount = field.NewString(tableName, "response_cost_amount")
	_modelCall.RetryCostAmount = field.NewString(tableName, "retry_cost_amount")
	_modelCall.BilledCostAmount = field.NewString(tableName, "billed_cost_amount")
	_modelCall.CostKnown = field.NewBool(tableName, "cost_known")
	_modelCall.FailureClassification = field.NewString(tableName, "failure_classification")
	_modelCall.FailureDetail = field.NewString(tableName, "failure_detail")
	_modelCall.StartedAt = field.NewTime(tableName, "started_at")
	_modelCall.CompletedAt = field.NewTime(tableName, "completed_at")

	_modelCall.fillFieldMap()

	return _modelCall
}

type modelCall struct {
	modelCallDo

	ALL                     field.Asterisk
	ID                      field.Field
	SessionID               field.Field
	ModelRunID              field.Field
	Round                   field.Int64
	RequestMessagesJSON     field.String
	RequestToolsJSON        field.String
	State                   field.String
	ResponseMessageJSON     field.String
	ResponseUsageJSON       field.String
	RetryAttemptsJSON       field.String
	RetryAttemptCount       field.Int64
	PromptTokens            field.Int64
	CompletionTokens        field.Int64
	TotalTokens             field.Int64
	ReasoningTokens         field.Int64
	CacheReadTokens         field.Int64
	CacheWriteTokens        field.Int64
	CacheWriteLongTTLTokens field.Int64
	WastedPromptTokens      field.Int64
	WastedCompletionTokens  field.Int64
	WastedTotalTokens       field.Int64
	TotalAttempts           field.Int64
	ResponseModelID         field.String
	FinishReason            field.String
	ResponseCostAmount      field.String
	RetryCostAmount         field.String
	BilledCostAmount        field.String
	CostKnown               field.Bool
	FailureClassification   field.String
	FailureDetail           field.String
	StartedAt               field.Time
	CompletedAt             field.Time

	fieldMap map[string]field.Expr
}

func (m modelCall) Table(newTableName string) *modelCall {
	m.modelCallDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m modelCall) As(alias string) *modelCall {
	m.modelCallDo.DO = *(m.modelCallDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *modelCall) updateTableName(table string) *modelCall {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewField(table, "id")
	m.SessionID = field.NewField(table, "session_id")
	m.ModelRunID = field.NewField(table, "model_run_id")
	m.Round = field.NewInt64(table, "round")
	m.RequestMessagesJSON = field.NewString(table, "request_messages_json")
	m.RequestToolsJSON = field.NewString(table, "request_tools_json")
	m.State = field.NewString(table, "state")
	m.ResponseMessageJSON = field.NewString(table, "response_message_json")
	m.ResponseUsageJSON = field.NewString(table, "response_usage_json")
	m.RetryAttemptsJSON = field.NewString(table, "retry_attempts_json")
	m.RetryAttemptCount = field.NewInt64(table, "retry_attempt_count")
	m.PromptTokens = field.NewInt64(table, "prompt_tokens")
	m.CompletionTokens = field.NewInt64(table, "completion_tokens")
	m.TotalTokens = field.NewInt64(table, "total_tokens")
	m.ReasoningTokens = field.NewInt64(table, "reasoning_tokens")
	m.CacheReadTokens = field.NewInt64(table, "cache_read_tokens")
	m.CacheWriteTokens = field.NewInt64(table, "cache_write_tokens")
	m.CacheWriteLongTTLTokens = field.NewInt64(table, "cache_write_long_ttl_tokens")
	m.WastedPromptTokens = field.NewInt64(table, "wasted_prompt_tokens")
	m.WastedCompletionTokens = field.NewInt64(table, "wasted_completion_tokens")
	m.WastedTotalTokens = field.NewInt64(table, "wasted_total_tokens")
	m.TotalAttempts = field.NewInt64(table, "total_attempts")
	m.ResponseModelID = field.NewString(table, "response_model_id")
	m.FinishReason = field.NewString(table, "finish_reason")
	m.ResponseCostAmount = field.NewString(table, "response_cost_amount")
	m.RetryCostAmount = field.NewString(table, "retry_cost_amount")
	m.BilledCostAmount = field.NewString(table, "billed_cost_amount")
	m.CostKnown = field.NewBool(table, "cost_known")
	m.FailureClassification = field.NewString(table, "failure_classification")
	m.FailureDetail = field.NewString(table, "failure_detail")
	m.StartedAt = field.NewTime(table, "started_at")
	m.CompletedAt = field.NewTime(table, "completed_at")

	m.fillFieldMap()

	return m
}

func (m *modelCall) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *modelCall) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 32)
	m.fieldMap["id"] = m.ID
	m.fieldMap["session_id"] = m.SessionID
	m.fieldMap["model_run_id"] = m.ModelRunID
	m.fieldMap["round"] = m.Round
	m.fieldMap["request_messages_json"] = m.RequestMessagesJSON
	m.fieldMap["request_tools_json"] = m.RequestToolsJSON
	m.fieldMap["state"] = m.State
	m.fieldMap["response_message_json"] = m.ResponseMessageJSON
	m.fieldMap["response_usage_json"] = m.ResponseUsageJSON
	m.fieldMap["retry_attempts_json"] = m.RetryAttemptsJSON
	m.fieldMap["retry_attempt_count"] = m.RetryAttemptCount
	m.fieldMap["prompt_tokens"] = m.PromptTokens
	m.fieldMap["completion_tokens"] = m.CompletionTokens
	m.fieldMap["total_tokens"] = m.TotalTokens
	m.fieldMap["reasoning_tokens"] = m.ReasoningTokens
	m.fieldMap["cache_read_tokens"] = m.CacheReadTokens
	m.fieldMap["cache_write_tokens"] = m.CacheWriteTokens
	m.fieldMap["cache_write_long_ttl_tokens"] = m.CacheWriteLongTTLTokens
	m.fieldMap["wasted_prompt_tokens"] = m.WastedPromptTokens
	m.fieldMap["wasted_completion_tokens"] = m.WastedCompletionTokens
	m.fieldMap["wasted_total_tokens"] = m.WastedTotalTokens
	m.fieldMap["total_attempts"] = m.TotalAttempts
	m.fieldMap["response_model_id"] = m.ResponseModelID
	m.fieldMap["finish_reason"] = m.FinishReason
	m.fieldMap["response_cost_amount"] = m.ResponseCostAmount
	m.fieldMap["retry_cost_amount"] = m.RetryCostAmount
	m.fieldMap["billed_cost_amount"] = m.BilledCostAmount
	m.fieldMap["cost_known"] = m.CostKnown
	m.fieldMap["failure_classification"] = m.FailureClassification
	m.fieldMap["failure_detail"] = m.FailureDetail
	m.fieldMap["started_at"] = m.StartedAt
	m.fieldMap["completed_at"] = m.CompletedAt
}

func (m modelCall) clone(db *gorm.DB) modelCall {
	m.modelCallDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m modelCall) replaceDB(db *gorm.DB) modelCall {
	m.modelCallDo.ReplaceDB(db)
	return m
}

type modelCallDo struct{ gen.DO }

type IModelCallDo interface {
	gen.SubQuery
	Debug() IModelCallDo
	WithContext(ctx context.Context) IModelCallDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IModelCallDo
	WriteDB() IModelCallDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IModelCallDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IModelCallDo
	Not(conds ...gen.Condition) IModelCallDo
	Or(conds ...gen.Condition) IModelCallDo
	Select(conds ...field.Expr) IModelCallDo
	Where(conds ...gen.Condition) IModelCallDo
	Order(conds ...field.Expr) IModelCallDo
	Distinct(cols ...field.Expr) IModelCallDo
	Omit(cols ...field.Expr) IModelCallDo
	Join(table schema.Tabler, on ...field.Expr) IModelCallDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IModelCallDo
	RightJoin(table schema.Tabler, on ...field.Expr) IModelCallDo
	Group(cols ...field.Expr) IModelCallDo
	Having(conds ...gen.Condition) IModelCallDo
	Limit(limit int) IModelCallDo
	Offset(offset int) IModelCallDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IModelCallDo
	Unscoped() IModelCallDo
	Create(values ...*models.ModelCall) error
	CreateInBatches(values []*models.ModelCall, batchSize int) error
	Save(values ...*models.ModelCall) error
	First() (*models.ModelCall, error)
	Take() (*models.ModelCall, error)
	Last() (*models.ModelCall, error)
	Find() ([]*models.ModelCall, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ModelCall, err error)
	FindInBatches(result *[]*models.ModelCall, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ModelCall) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IModelCallDo
	Assign(attrs ...field.AssignExpr) IModelCallDo
	Joins(fields ...field.RelationField) IModelCallDo
	Preload(fields ...field.RelationField) IModelCallDo
	FirstOrInit() (*models.ModelCall, error)
	FirstOrCreate() (*models.ModelCall, error)
	FindByPage(offset int, limit int) (result []*models.ModelCall, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IModelCallDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m modelCallDo) Debug() IModelCallDo {
	return m.withDO(m.DO.Debug())
}

func (m modelCallDo) WithContext(ctx context.Context) IModelCallDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m modelCallDo) ReadDB() IModelCallDo {
	return m.Clauses(dbresolver.Read)
}

func (m modelCallDo) WriteDB() IModelCallDo {
	return m.Clauses(dbresolver.Write)
}

func (m modelCallDo) Session(config *gorm.Session) IModelCallDo {
	return m.withDO(m.DO.Session(config))
}

func (m modelCallDo) Clauses(conds ...clause.Expression) IModelCallDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m modelCallDo) Returning(value interface{}, columns ...string) IModelCallDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m modelCallDo) Not(conds ...gen.Condition) IModelCallDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m modelCallDo) Or(conds ...gen.Condition) IModelCallDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m modelCallDo) Select(conds ...field.Expr) IModelCallDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m modelCallDo) Where(conds ...gen.Condition) IModelCallDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m modelCallDo) Order(conds ...field.Expr) IModelCallDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m modelCallDo) Distinct(cols ...field.Expr) IModelCallDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m modelCallDo) Omit(cols ...field.Expr) IModelCallDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m modelCallDo) Join(table schema.Tabler, on ...field.Expr) IModelCallDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m modelCallDo) LeftJoin(table schema.Tabler, on ...field.Expr) IModelCallDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m modelCallDo) RightJoin(table schema.Tabler, on ...field.Expr) IModelCallDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m modelCallDo) Group(cols ...field.Expr) IModelCallDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m modelCallDo) Having(conds ...gen.Condition) IModelCallDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m modelCallDo) Limit(limit int) IModelCallDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m modelCallDo) Offset(offset int) IModelCallDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m modelCallDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IModelCallDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m modelCallDo) Unscoped() IModelCallDo {
	return m.withDO(m.DO.Unscoped())
}

func (m modelCallDo) Create(values ...*models.ModelCall) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m modelCallDo) CreateInBatches(values []*models.ModelCall, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m modelCallDo) Save(values ...*models.ModelCall) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m modelCallDo) First() (*models.ModelCall, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ModelCall), nil
	}
}

func (m modelCallDo) Take() (*models.ModelCall, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ModelCall), nil
	}
}

func (m modelCallDo) Last() (*models.ModelCall, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ModelCall), nil
	}
}

func (m modelCallDo) Find() ([]*models.ModelCall, error) {
	result, err := m.DO.Find()
	return result.([]*models.ModelCall), err
}

func (m modelCallDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ModelCall, err error) {
	buf := make([]*models.ModelCall, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m modelCallDo) FindInBatches(result *[]*models.ModelCall, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m modelCallDo) Attrs(attrs ...field.AssignExpr) IModelCallDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m modelCallDo) Assign(attrs ...field.AssignExpr) IModelCallDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m modelCallDo) Joins(fields ...field.RelationField) IModelCallDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m modelCallDo) Preload(fields ...field.RelationField) IModelCallDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m modelCallDo) FirstOrInit() (*models.ModelCall, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ModelCall), nil
	}
}

func (m modelCallDo) FirstOrCreate() (*models.ModelCall, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ModelCall), nil
	}
}

func (m modelCallDo) FindByPage(offset int, limit int) (result []*models.ModelCall, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m modelCallDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m modelCallDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m modelCallDo) Delete(models ...*models.ModelCall) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *modelCallDo) withDO(do gen.Dao) *modelCallDo {
	m.DO = *do.(*gen.DO)
	return m
}
