// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/peen/internal/pkg/db/models"
)

func newModelRun(db *gorm.DB, opts ...gen.DOOption) modelRun {
	_modelRun := modelRun{}

	_modelRun.modelRunDo.UseDB(db, opts...)
	_modelRun.modelRunDo.UseModel(&models.ModelRun{})

	tableName := _modelRun.modelRunDo.TableName()
	_modelRun.ALL = field.NewAsterisk(tableName)
	_modelRun.ID = field.NewField(tableName, "id")
	_modelRun.SessionID = field.NewField(tableName, "session_id")
	_modelRun.TurnID = field.NewField(tableName, "turn_id")
	_modelRun.AgentRunID = field.NewField(tableName, "agent_run_id")
	_modelRun.Stage = field.NewString(tableName, "stage")
	_modelRun.ModelReference = field.NewString(tableName, "model_reference")
	_modelRun.ConnectionName = field.NewString(tableName, "connection_name")
	_modelRun.RequestedModelID = field.NewString(tableName, "requested_model_id")
	_modelRun.ResponseModelID = field.NewString(tableName, "response_model_id")
	_modelRun.RequestSettingsJSON = field.NewString(tableName, "request_settings_json")
	_modelRun.State = field.NewString(tableName, "state")
	_modelRun.ResponseText = field.NewString(tableName, "response_text")
	_modelRun.ResponseThinking = field.NewString(tableName, "response_thinking")
	_modelRun.ResponseMessagesJSON = field.NewString(tableName, "response_messages_json")
	_modelRun.ResponseInjectionsJSON = field.NewString(tableName, "response_injections_json")
	_modelRun.ResponseUsageJSON = field.NewString(tableName, "response_usage_json")
	_modelRun.ResponseCostAmount = field.NewString(tableName, "response_cost_amount")
	_modelRun.RetryCostAmount = field.NewString(tableName, "retry_cost_amount")
	_modelRun.BilledCostAmount = field.NewString(tableName, "billed_cost_amount")
	_modelRun.CostKnown = field.NewBool(tableName, "cost_known")
	_modelRun.FinishReason = field.NewString(tableName, "finish_reason")
	_modelRun.FailureClassification = field.NewString(tableName, "failure_classification")
	_modelRun.FailureDetail = field.NewString(tableName, "failure_detail")
	_modelRun.StartedAt = field.NewTime(tableName, "started_at")
	_modelRun.CompletedAt = field.NewTime(tableName, "completed_at")

	_modelRun.fillFieldMap()

	return _modelRun
}

type modelRun struct {
	modelRunDo

	ALL                    field.Asterisk
	ID                     field.Field
	SessionID              field.Field
	TurnID                 field.Field
	AgentRunID             field.Field
	Stage                  field.String
	ModelReference         field.String
	ConnectionName         field.String
	RequestedModelID       field.String
	ResponseModelID        field.String
	RequestSettingsJSON    field.String
	State                  field.String
	ResponseText           field.String
	ResponseThinking       field.String
	ResponseMessagesJSON   field.String
	ResponseInjectionsJSON field.String
	ResponseUsageJSON      field.String
	ResponseCostAmount     field.String
	RetryCostAmount        field.String
	BilledCostAmount       field.String
	CostKnown              field.Bool
	FinishReason           field.String
	FailureClassification  field.String
	FailureDetail          field.String
	StartedAt              field.Time
	CompletedAt            field.Time

	fieldMap map[string]field.Expr
}

func (m modelRun) Table(newTableName string) *modelRun {
	m.modelRunDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m modelRun) As(alias string) *modelRun {
	m.modelRunDo.DO = *(m.modelRunDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *modelRun) updateTableName(table string) *modelRun {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewField(table, "id")
	m.SessionID = field.NewField(table, "session_id")
	m.TurnID = field.NewField(table, "turn_id")
	m.AgentRunID = field.NewField(table, "agent_run_id")
	m.Stage = field.NewString(table, "stage")
	m.ModelReference = field.NewString(table, "model_reference")
	m.ConnectionName = field.NewString(table, "connection_name")
	m.RequestedModelID = field.NewString(table, "requested_model_id")
	m.ResponseModelID = field.NewString(table, "response_model_id")
	m.RequestSettingsJSON = field.NewString(table, "request_settings_json")
	m.State = field.NewString(table, "state")
	m.ResponseText = field.NewString(table, "response_text")
	m.ResponseThinking = field.NewString(table, "response_thinking")
	m.ResponseMessagesJSON = field.NewString(table, "response_messages_json")
	m.ResponseInjectionsJSON = field.NewString(table, "response_injections_json")
	m.ResponseUsageJSON = field.NewString(table, "response_usage_json")
	m.ResponseCostAmount = field.NewString(table, "response_cost_amount")
	m.RetryCostAmount = field.NewString(table, "retry_cost_amount")
	m.BilledCostAmount = field.NewString(table, "billed_cost_amount")
	m.CostKnown = field.NewBool(table, "cost_known")
	m.FinishReason = field.NewString(table, "finish_reason")
	m.FailureClassification = field.NewString(table, "failure_classification")
	m.FailureDetail = field.NewString(table, "failure_detail")
	m.StartedAt = field.NewTime(table, "started_at")
	m.CompletedAt = field.NewTime(table, "completed_at")

	m.fillFieldMap()

	return m
}

func (m *modelRun) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *modelRun) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 25)
	m.fieldMap["id"] = m.ID
	m.fieldMap["session_id"] = m.SessionID
	m.fieldMap["turn_id"] = m.TurnID
	m.fieldMap["agent_run_id"] = m.AgentRunID
	m.fieldMap["stage"] = m.Stage
	m.fieldMap["model_reference"] = m.ModelReference
	m.fieldMap["connection_name"] = m.ConnectionName
	m.fieldMap["requested_model_id"] = m.RequestedModelID
	m.fieldMap["response_model_id"] = m.ResponseModelID
	m.fieldMap["request_settings_json"] = m.RequestSettingsJSON
	m.fieldMap["state"] = m.State
	m.fieldMap["response_text"] = m.ResponseText
	m.fieldMap["response_thinking"] = m.ResponseThinking
	m.fieldMap["response_messages_json"] = m.ResponseMessagesJSON
	m.fieldMap["response_injections_json"] = m.ResponseInjectionsJSON
	m.fieldMap["response_usage_json"] = m.ResponseUsageJSON
	m.fieldMap["response_cost_amount"] = m.ResponseCostAmount
	m.fieldMap["retry_cost_amount"] = m.RetryCostAmount
	m.fieldMap["billed_cost_amount"] = m.BilledCostAmount
	m.fieldMap["cost_known"] = m.CostKnown
	m.fieldMap["finish_reason"] = m.FinishReason
	m.fieldMap["failure_classification"] = m.FailureClassification
	m.fieldMap["failure_detail"] = m.FailureDetail
	m.fieldMap["started_at"] = m.StartedAt
	m.fieldMap["completed_at"] = m.CompletedAt
}

func (m modelRun) clone(db *gorm.DB) modelRun {
	m.modelRunDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m modelRun) replaceDB(db *gorm.DB) modelRun {
	m.modelRunDo.ReplaceDB(db)
	return m
}

type modelRunDo struct{ gen.DO }

type IModelRunDo interface {
	gen.SubQuery
	Debug() IModelRunDo
	WithContext(ctx context.Context) IModelRunDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IModelRunDo
	WriteDB() IModelRunDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IModelRunDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IModelRunDo
	Not(conds ...gen.Condition) IModelRunDo
	Or(conds ...gen.Condition) IModelRunDo
	Select(conds ...field.Expr) IModelRunDo
	Where(conds ...gen.Condition) IModelRunDo
	Order(conds ...field.Expr) IModelRunDo
	Distinct(cols ...field.Expr) IModelRunDo
	Omit(cols ...field.Expr) IModelRunDo
	Join(table schema.Tabler, on ...field.Expr) IModelRunDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IModelRunDo
	RightJoin(table schema.Tabler, on ...field.Expr) IModelRunDo
	Group(cols ...field.Expr) IModelRunDo
	Having(conds ...gen.Condition) IModelRunDo
	Limit(limit int) IModelRunDo
	Offset(offset int) IModelRunDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IModelRunDo
	Unscoped() IModelRunDo
	Create(values ...*models.ModelRun) error
	CreateInBatches(values []*models.ModelRun, batchSize int) error
	Save(values ...*models.ModelRun) error
	First() (*models.ModelRun, error)
	Take() (*models.ModelRun, error)
	Last() (*models.ModelRun, error)
	Find() ([]*models.ModelRun, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ModelRun, err error)
	FindInBatches(result *[]*models.ModelRun, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ModelRun) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IModelRunDo
	Assign(attrs ...field.AssignExpr) IModelRunDo
	Joins(fields ...field.RelationField) IModelRunDo
	Preload(fields ...field.RelationField) IModelRunDo
	FirstOrInit() (*models.ModelRun, error)
	FirstOrCreate() (*models.ModelRun, error)
	FindByPage(offset int, limit int) (result []*models.ModelRun, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IModelRunDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m modelRunDo) Debug() IModelRunDo {
	return m.withDO(m.DO.Debug())
}

func (m modelRunDo) WithContext(ctx context.Context) IModelRunDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m modelRunDo) ReadDB() IModelRunDo {
	return m.Clauses(dbresolver.Read)
}

func (m modelRunDo) WriteDB() IModelRunDo {
	return m.Clauses(dbresolver.Write)
}

func (m modelRunDo) Session(config *gorm.Session) IModelRunDo {
	return m.withDO(m.DO.Session(config))
}

func (m modelRunDo) Clauses(conds ...clause.Expression) IModelRunDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m modelRunDo) Returning(value interface{}, columns ...string) IModelRunDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m modelRunDo) Not(conds ...gen.Condition) IModelRunDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m modelRunDo) Or(conds ...gen.Condition) IModelRunDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m modelRunDo) Select(conds ...field.Expr) IModelRunDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m modelRunDo) Where(conds ...gen.Condition) IModelRunDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m modelRunDo) Order(conds ...field.Expr) IModelRunDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m modelRunDo) Distinct(cols ...field.Expr) IModelRunDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m modelRunDo) Omit(cols ...field.Expr) IModelRunDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m modelRunDo) Join(table schema.Tabler, on ...field.Expr) IModelRunDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m modelRunDo) LeftJoin(table schema.Tabler, on ...field.Expr) IModelRunDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m modelRunDo) RightJoin(table schema.Tabler, on ...field.Expr) IModelRunDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m modelRunDo) Group(cols ...field.Expr) IModelRunDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m modelRunDo) Having(conds ...gen.Condition) IModelRunDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m modelRunDo) Limit(limit int) IModelRunDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m modelRunDo) Offset(offset int) IModelRunDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m modelRunDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IModelRunDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m modelRunDo) Unscoped() IModelRunDo {
	return m.withDO(m.DO.Unscoped())
}

func (m modelRunDo) Create(values ...*models.ModelRun) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m modelRunDo) CreateInBatches(values []*models.ModelRun, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m modelRunDo) Save(values ...*models.ModelRun) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m modelRunDo) First() (*models.ModelRun, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ModelRun), nil
	}
}

func (m modelRunDo) Take() (*models.ModelRun, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ModelRun), nil
	}
}

func (m modelRunDo) Last() (*models.ModelRun, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ModelRun), nil
	}
}

func (m modelRunDo) Find() ([]*models.ModelRun, error) {
	result, err := m.DO.Find()
	return result.([]*models.ModelRun), err
}

func (m modelRunDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ModelRun, err error) {
	buf := make([]*models.ModelRun, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m modelRunDo) FindInBatches(result *[]*models.ModelRun, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m modelRunDo) Attrs(attrs ...field.AssignExpr) IModelRunDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m modelRunDo) Assign(attrs ...field.AssignExpr) IModelRunDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m modelRunDo) Joins(fields ...field.RelationField) IModelRunDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m modelRunDo) Preload(fields ...field.RelationField) IModelRunDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m modelRunDo) FirstOrInit() (*models.ModelRun, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ModelRun), nil
	}
}

func (m modelRunDo) FirstOrCreate() (*models.ModelRun, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ModelRun), nil
	}
}

func (m modelRunDo) FindByPage(offset int, limit int) (result []*models.ModelRun, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m modelRunDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m modelRunDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m modelRunDo) Delete(models ...*models.ModelRun) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *modelRunDo) withDO(do gen.Dao) *modelRunDo {
	m.DO = *do.(*gen.DO)
	return m
}
