// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/peen/internal/pkg/db/models"
)

func newPromptSnapshot(db *gorm.DB, opts ...gen.DOOption) promptSnapshot {
	_promptSnapshot := promptSnapshot{}

	_promptSnapshot.promptSnapshotDo.UseDB(db, opts...)
	_promptSnapshot.promptSnapshotDo.UseModel(&models.PromptSnapshot{})

	tableName := _promptSnapshot.promptSnapshotDo.TableName()
	_promptSnapshot.ALL = field.NewAsterisk(tableName)
	_promptSnapshot.Hash = field.NewString(tableName, "hash")
	_promptSnapshot.EffectivePrompt = field.NewString(tableName, "effective_prompt")
	_promptSnapshot.CreatedAt = field.NewTime(tableName, "created_at")

	_promptSnapshot.fillFieldMap()

	return _promptSnapshot
}

type promptSnapshot struct {
	promptSnapshotDo

	ALL             field.Asterisk
	Hash            field.String
	EffectivePrompt field.String
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (p promptSnapshot) Table(newTableName string) *promptSnapshot {
	p.promptSnapshotDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promptSnapshot) As(alias string) *promptSnapshot {
	p.promptSnapshotDo.DO = *(p.promptSnapshotDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promptSnapshot) updateTableName(table string) *promptSnapshot {
	p.ALL = field.NewAsterisk(table)
	p.Hash = field.NewString(table, "hash")
	p.EffectivePrompt = field.NewString(table, "effective_prompt")
	p.CreatedAt = field.NewTime(table, "created_at")

	p.fillFieldMap()

	return p
}

func (p *promptSnapshot) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promptSnapshot) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["hash"] = p.Hash
	p.fieldMap["effective_prompt"] = p.EffectivePrompt
	p.fieldMap["created_at"] = p.CreatedAt
}

func (p promptSnapshot) clone(db *gorm.DB) promptSnapshot {
	p.promptSnapshotDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promptSnapshot) replaceDB(db *gorm.DB) promptSnapshot {
	p.promptSnapshotDo.ReplaceDB(db)
	return p
}

type promptSnapshotDo struct{ gen.DO }

type IPromptSnapshotDo interface {
	gen.SubQuery
	Debug() IPromptSnapshotDo
	WithContext(ctx context.Context) IPromptSnapshotDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromptSnapshotDo
	WriteDB() IPromptSnapshotDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromptSnapshotDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromptSnapshotDo
	Not(conds ...gen.Condition) IPromptSnapshotDo
	Or(conds ...gen.Condition) IPromptSnapshotDo
	Select(conds ...field.Expr) IPromptSnapshotDo
	Where(conds ...gen.Condition) IPromptSnapshotDo
	Order(conds ...field.Expr) IPromptSnapshotDo
	Distinct(cols ...field.Expr) IPromptSnapshotDo
	Omit(cols ...field.Expr) IPromptSnapshotDo
	Join(table schema.Tabler, on ...field.Expr) IPromptSnapshotDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromptSnapshotDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromptSnapshotDo
	Group(cols ...field.Expr) IPromptSnapshotDo
	Having(conds ...gen.Condition) IPromptSnapshotDo
	Limit(limit int) IPromptSnapshotDo
	Offset(offset int) IPromptSnapshotDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromptSnapshotDo
	Unscoped() IPromptSnapshotDo
	Create(values ...*models.PromptSnapshot) error
	CreateInBatches(values []*models.PromptSnapshot, batchSize int) error
	Save(values ...*models.PromptSnapshot) error
	First() (*models.PromptSnapshot, error)
	Take() (*models.PromptSnapshot, error)
	Last() (*models.PromptSnapshot, error)
	Find() ([]*models.PromptSnapshot, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.PromptSnapshot, err error)
	FindInBatches(result *[]*models.PromptSnapshot, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.PromptSnapshot) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromptSnapshotDo
	Assign(attrs ...field.AssignExpr) IPromptSnapshotDo
	Joins(fields ...field.RelationField) IPromptSnapshotDo
	Preload(fields ...field.RelationField) IPromptSnapshotDo
	FirstOrInit() (*models.PromptSnapshot, error)
	FirstOrCreate() (*models.PromptSnapshot, error)
	FindByPage(offset int, limit int) (result []*models.PromptSnapshot, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromptSnapshotDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promptSnapshotDo) Debug() IPromptSnapshotDo {
	return p.withDO(p.DO.Debug())
}

func (p promptSnapshotDo) WithContext(ctx context.Context) IPromptSnapshotDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promptSnapshotDo) ReadDB() IPromptSnapshotDo {
	return p.Clauses(dbresolver.Read)
}

func (p promptSnapshotDo) WriteDB() IPromptSnapshotDo {
	return p.Clauses(dbresolver.Write)
}

func (p promptSnapshotDo) Session(config *gorm.Session) IPromptSnapshotDo {
	return p.withDO(p.DO.Session(config))
}

func (p promptSnapshotDo) Clauses(conds ...clause.Expression) IPromptSnapshotDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promptSnapshotDo) Returning(value interface{}, columns ...string) IPromptSnapshotDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promptSnapshotDo) Not(conds ...gen.Condition) IPromptSnapshotDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promptSnapshotDo) Or(conds ...gen.Condition) IPromptSnapshotDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promptSnapshotDo) Select(conds ...field.Expr) IPromptSnapshotDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promptSnapshotDo) Where(conds ...gen.Condition) IPromptSnapshotDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promptSnapshotDo) Order(conds ...field.Expr) IPromptSnapshotDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promptSnapshotDo) Distinct(cols ...field.Expr) IPromptSnapshotDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promptSnapshotDo) Omit(cols ...field.Expr) IPromptSnapshotDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promptSnapshotDo) Join(table schema.Tabler, on ...field.Expr) IPromptSnapshotDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promptSnapshotDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromptSnapshotDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promptSnapshotDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromptSnapshotDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promptSnapshotDo) Group(cols ...field.Expr) IPromptSnapshotDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promptSnapshotDo) Having(conds ...gen.Condition) IPromptSnapshotDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promptSnapshotDo) Limit(limit int) IPromptSnapshotDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promptSnapshotDo) Offset(offset int) IPromptSnapshotDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promptSnapshotDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromptSnapshotDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promptSnapshotDo) Unscoped() IPromptSnapshotDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promptSnapshotDo) Create(values ...*models.PromptSnapshot) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promptSnapshotDo) CreateInBatches(values []*models.PromptSnapshot, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promptSnapshotDo) Save(values ...*models.PromptSnapshot) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promptSnapshotDo) First() (*models.PromptSnapshot, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.PromptSnapshot), nil
	}
}

func (p promptSnapshotDo) Take() (*models.PromptSnapshot, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.PromptSnapshot), nil
	}
}

func (p promptSnapshotDo) Last() (*models.PromptSnapshot, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.PromptSnapshot), nil
	}
}

func (p promptSnapshotDo) Find() ([]*models.PromptSnapshot, error) {
	result, err := p.DO.Find()
	return result.([]*models.PromptSnapshot), err
}

func (p promptSnapshotDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.PromptSnapshot, err error) {
	buf := make([]*models.PromptSnapshot, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promptSnapshotDo) FindInBatches(result *[]*models.PromptSnapshot, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promptSnapshotDo) Attrs(attrs ...field.AssignExpr) IPromptSnapshotDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promptSnapshotDo) Assign(attrs ...field.AssignExpr) IPromptSnapshotDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promptSnapshotDo) Joins(fields ...field.RelationField) IPromptSnapshotDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promptSnapshotDo) Preload(fields ...field.RelationField) IPromptSnapshotDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promptSnapshotDo) FirstOrInit() (*models.PromptSnapshot, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.PromptSnapshot), nil
	}
}

func (p promptSnapshotDo) FirstOrCreate() (*models.PromptSnapshot, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.PromptSnapshot), nil
	}
}

func (p promptSnapshotDo) FindByPage(offset int, limit int) (result []*models.PromptSnapshot, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promptSnapshotDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promptSnapshotDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promptSnapshotDo) Delete(models ...*models.PromptSnapshot) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promptSnapshotDo) withDO(do gen.Dao) *promptSnapshotDo {
	p.DO = *do.(*gen.DO)
	return p
}
