// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query)
	AgentRun         *agentRun
	AgentRunEvent    *agentRunEvent
	Compaction       *compaction
	ContextSnapshot  *contextSnapshot
	Event            *event
	Job              *job
	JobOutputLine    *jobOutputLine
	JobSignalRequest *jobSignalRequest
	Message          *message
	ModelCall        *modelCall
	ModelRun         *modelRun
	PromptSnapshot   *promptSnapshot
	Session          *session
	SessionNotice    *sessionNotice
	Turn             *turn
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AgentRun = &Q.AgentRun
	AgentRunEvent = &Q.AgentRunEvent
	Compaction = &Q.Compaction
	ContextSnapshot = &Q.ContextSnapshot
	Event = &Q.Event
	Job = &Q.Job
	JobOutputLine = &Q.JobOutputLine
	JobSignalRequest = &Q.JobSignalRequest
	Message = &Q.Message
	ModelCall = &Q.ModelCall
	ModelRun = &Q.ModelRun
	PromptSnapshot = &Q.PromptSnapshot
	Session = &Q.Session
	SessionNotice = &Q.SessionNotice
	Turn = &Q.Turn
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		AgentRun:         newAgentRun(db, opts...),
		AgentRunEvent:    newAgentRunEvent(db, opts...),
		Compaction:       newCompaction(db, opts...),
		ContextSnapshot:  newContextSnapshot(db, opts...),
		Event:            newEvent(db, opts...),
		Job:              newJob(db, opts...),
		JobOutputLine:    newJobOutputLine(db, opts...),
		JobSignalRequest: newJobSignalRequest(db, opts...),
		Message:          newMessage(db, opts...),
		ModelCall:        newModelCall(db, opts...),
		ModelRun:         newModelRun(db, opts...),
		PromptSnapshot:   newPromptSnapshot(db, opts...),
		Session:          newSession(db, opts...),
		SessionNotice:    newSessionNotice(db, opts...),
		Turn:             newTurn(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AgentRun         agentRun
	AgentRunEvent    agentRunEvent
	Compaction       compaction
	ContextSnapshot  contextSnapshot
	Event            event
	Job              job
	JobOutputLine    jobOutputLine
	JobSignalRequest jobSignalRequest
	Message          message
	ModelCall        modelCall
	ModelRun         modelRun
	PromptSnapshot   promptSnapshot
	Session          session
	SessionNotice    sessionNotice
	Turn             turn
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		AgentRun:         q.AgentRun.clone(db),
		AgentRunEvent:    q.AgentRunEvent.clone(db),
		Compaction:       q.Compaction.clone(db),
		ContextSnapshot:  q.ContextSnapshot.clone(db),
		Event:            q.Event.clone(db),
		Job:              q.Job.clone(db),
		JobOutputLine:    q.JobOutputLine.clone(db),
		JobSignalRequest: q.JobSignalRequest.clone(db),
		Message:          q.Message.clone(db),
		ModelCall:        q.ModelCall.clone(db),
		ModelRun:         q.ModelRun.clone(db),
		PromptSnapshot:   q.PromptSnapshot.clone(db),
		Session:          q.Session.clone(db),
		SessionNotice:    q.SessionNotice.clone(db),
		Turn:             q.Turn.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		AgentRun:         q.AgentRun.replaceDB(db),
		AgentRunEvent:    q.AgentRunEvent.replaceDB(db),
		Compaction:       q.Compaction.replaceDB(db),
		ContextSnapshot:  q.ContextSnapshot.replaceDB(db),
		Event:            q.Event.replaceDB(db),
		Job:              q.Job.replaceDB(db),
		JobOutputLine:    q.JobOutputLine.replaceDB(db),
		JobSignalRequest: q.JobSignalRequest.replaceDB(db),
		Message:          q.Message.replaceDB(db),
		ModelCall:        q.ModelCall.replaceDB(db),
		ModelRun:         q.ModelRun.replaceDB(db),
		PromptSnapshot:   q.PromptSnapshot.replaceDB(db),
		Session:          q.Session.replaceDB(db),
		SessionNotice:    q.SessionNotice.replaceDB(db),
		Turn:             q.Turn.replaceDB(db),
	}
}

type queryCtx struct {
	AgentRun         IAgentRunDo
	AgentRunEvent    IAgentRunEventDo
	Compaction       ICompactionDo
	ContextSnapshot  IContextSnapshotDo
	Event            IEventDo
	Job              IJobDo
	JobOutputLine    IJobOutputLineDo
	JobSignalRequest IJobSignalRequestDo
	Message          IMessageDo
	ModelCall        IModelCallDo
	ModelRun         IModelRunDo
	PromptSnapshot   IPromptSnapshotDo
	Session          ISessionDo
	SessionNotice    ISessionNoticeDo
	Turn             ITurnDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AgentRun:         q.AgentRun.WithContext(ctx),
		AgentRunEvent:    q.AgentRunEvent.WithContext(ctx),
		Compaction:       q.Compaction.WithContext(ctx),
		ContextSnapshot:  q.ContextSnapshot.WithContext(ctx),
		Event:            q.Event.WithContext(ctx),
		Job:              q.Job.WithContext(ctx),
		JobOutputLine:    q.JobOutputLine.WithContext(ctx),
		JobSignalRequest: q.JobSignalRequest.WithContext(ctx),
		Message:          q.Message.WithContext(ctx),
		ModelCall:        q.ModelCall.WithContext(ctx),
		ModelRun:         q.ModelRun.WithContext(ctx),
		PromptSnapshot:   q.PromptSnapshot.WithContext(ctx),
		Session:          q.Session.WithContext(ctx),
		SessionNotice:    q.SessionNotice.WithContext(ctx),
		Turn:             q.Turn.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
