// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	Compaction      *compaction
	ContextSnapshot *contextSnapshot
	Event           *event
	Message         *message
	PromptSnapshot  *promptSnapshot
	Session         *session
	Turn            *turn
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Compaction = &Q.Compaction
	ContextSnapshot = &Q.ContextSnapshot
	Event = &Q.Event
	Message = &Q.Message
	PromptSnapshot = &Q.PromptSnapshot
	Session = &Q.Session
	Turn = &Q.Turn
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Compaction:      newCompaction(db, opts...),
		ContextSnapshot: newContextSnapshot(db, opts...),
		Event:           newEvent(db, opts...),
		Message:         newMessage(db, opts...),
		PromptSnapshot:  newPromptSnapshot(db, opts...),
		Session:         newSession(db, opts...),
		Turn:            newTurn(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Compaction      compaction
	ContextSnapshot contextSnapshot
	Event           event
	Message         message
	PromptSnapshot  promptSnapshot
	Session         session
	Turn            turn
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Compaction:      q.Compaction.clone(db),
		ContextSnapshot: q.ContextSnapshot.clone(db),
		Event:           q.Event.clone(db),
		Message:         q.Message.clone(db),
		PromptSnapshot:  q.PromptSnapshot.clone(db),
		Session:         q.Session.clone(db),
		Turn:            q.Turn.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Compaction:      q.Compaction.replaceDB(db),
		ContextSnapshot: q.ContextSnapshot.replaceDB(db),
		Event:           q.Event.replaceDB(db),
		Message:         q.Message.replaceDB(db),
		PromptSnapshot:  q.PromptSnapshot.replaceDB(db),
		Session:         q.Session.replaceDB(db),
		Turn:            q.Turn.replaceDB(db),
	}
}

type queryCtx struct {
	Compaction      ICompactionDo
	ContextSnapshot IContextSnapshotDo
	Event           IEventDo
	Message         IMessageDo
	PromptSnapshot  IPromptSnapshotDo
	Session         ISessionDo
	Turn            ITurnDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Compaction:      q.Compaction.WithContext(ctx),
		ContextSnapshot: q.ContextSnapshot.WithContext(ctx),
		Event:           q.Event.WithContext(ctx),
		Message:         q.Message.WithContext(ctx),
		PromptSnapshot:  q.PromptSnapshot.WithContext(ctx),
		Session:         q.Session.WithContext(ctx),
		Turn:            q.Turn.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
