// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/peen/internal/pkg/db/models"
)

func newSessionNotice(db *gorm.DB, opts ...gen.DOOption) sessionNotice {
	_sessionNotice := sessionNotice{}

	_sessionNotice.sessionNoticeDo.UseDB(db, opts...)
	_sessionNotice.sessionNoticeDo.UseModel(&models.SessionNotice{})

	tableName := _sessionNotice.sessionNoticeDo.TableName()
	_sessionNotice.ALL = field.NewAsterisk(tableName)
	_sessionNotice.ID = field.NewField(tableName, "id")
	_sessionNotice.SessionID = field.NewField(tableName, "session_id")
	_sessionNotice.Sequence = field.NewInt64(tableName, "sequence")
	_sessionNotice.Type = field.NewString(tableName, "type")
	_sessionNotice.Source = field.NewString(tableName, "source")
	_sessionNotice.Summary = field.NewString(tableName, "summary")
	_sessionNotice.DataJSON = field.NewString(tableName, "data_json")
	_sessionNotice.Delivery = field.NewString(tableName, "delivery")
	_sessionNotice.State = field.NewString(tableName, "state")
	_sessionNotice.CreatedAt = field.NewTime(tableName, "created_at")
	_sessionNotice.DeliveredAt = field.NewTime(tableName, "delivered_at")

	_sessionNotice.fillFieldMap()

	return _sessionNotice
}

type sessionNotice struct {
	sessionNoticeDo

	ALL         field.Asterisk
	ID          field.Field
	SessionID   field.Field
	Sequence    field.Int64
	Type        field.String
	Source      field.String
	Summary     field.String
	DataJSON    field.String
	Delivery    field.String
	State       field.String
	CreatedAt   field.Time
	DeliveredAt field.Time

	fieldMap map[string]field.Expr
}

func (s sessionNotice) Table(newTableName string) *sessionNotice {
	s.sessionNoticeDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sessionNotice) As(alias string) *sessionNotice {
	s.sessionNoticeDo.DO = *(s.sessionNoticeDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sessionNotice) updateTableName(table string) *sessionNotice {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewField(table, "id")
	s.SessionID = field.NewField(table, "session_id")
	s.Sequence = field.NewInt64(table, "sequence")
	s.Type = field.NewString(table, "type")
	s.Source = field.NewString(table, "source")
	s.Summary = field.NewString(table, "summary")
	s.DataJSON = field.NewString(table, "data_json")
	s.Delivery = field.NewString(table, "delivery")
	s.State = field.NewString(table, "state")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.DeliveredAt = field.NewTime(table, "delivered_at")

	s.fillFieldMap()

	return s
}

func (s *sessionNotice) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sessionNotice) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["session_id"] = s.SessionID
	s.fieldMap["sequence"] = s.Sequence
	s.fieldMap["type"] = s.Type
	s.fieldMap["source"] = s.Source
	s.fieldMap["summary"] = s.Summary
	s.fieldMap["data_json"] = s.DataJSON
	s.fieldMap["delivery"] = s.Delivery
	s.fieldMap["state"] = s.State
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["delivered_at"] = s.DeliveredAt
}

func (s sessionNotice) clone(db *gorm.DB) sessionNotice {
	s.sessionNoticeDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sessionNotice) replaceDB(db *gorm.DB) sessionNotice {
	s.sessionNoticeDo.ReplaceDB(db)
	return s
}

type sessionNoticeDo struct{ gen.DO }

type ISessionNoticeDo interface {
	gen.SubQuery
	Debug() ISessionNoticeDo
	WithContext(ctx context.Context) ISessionNoticeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISessionNoticeDo
	WriteDB() ISessionNoticeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISessionNoticeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISessionNoticeDo
	Not(conds ...gen.Condition) ISessionNoticeDo
	Or(conds ...gen.Condition) ISessionNoticeDo
	Select(conds ...field.Expr) ISessionNoticeDo
	Where(conds ...gen.Condition) ISessionNoticeDo
	Order(conds ...field.Expr) ISessionNoticeDo
	Distinct(cols ...field.Expr) ISessionNoticeDo
	Omit(cols ...field.Expr) ISessionNoticeDo
	Join(table schema.Tabler, on ...field.Expr) ISessionNoticeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISessionNoticeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISessionNoticeDo
	Group(cols ...field.Expr) ISessionNoticeDo
	Having(conds ...gen.Condition) ISessionNoticeDo
	Limit(limit int) ISessionNoticeDo
	Offset(offset int) ISessionNoticeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISessionNoticeDo
	Unscoped() ISessionNoticeDo
	Create(values ...*models.SessionNotice) error
	CreateInBatches(values []*models.SessionNotice, batchSize int) error
	Save(values ...*models.SessionNotice) error
	First() (*models.SessionNotice, error)
	Take() (*models.SessionNotice, error)
	Last() (*models.SessionNotice, error)
	Find() ([]*models.SessionNotice, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SessionNotice, err error)
	FindInBatches(result *[]*models.SessionNotice, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SessionNotice) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISessionNoticeDo
	Assign(attrs ...field.AssignExpr) ISessionNoticeDo
	Joins(fields ...field.RelationField) ISessionNoticeDo
	Preload(fields ...field.RelationField) ISessionNoticeDo
	FirstOrInit() (*models.SessionNotice, error)
	FirstOrCreate() (*models.SessionNotice, error)
	FindByPage(offset int, limit int) (result []*models.SessionNotice, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISessionNoticeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sessionNoticeDo) Debug() ISessionNoticeDo {
	return s.withDO(s.DO.Debug())
}

func (s sessionNoticeDo) WithContext(ctx context.Context) ISessionNoticeDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sessionNoticeDo) ReadDB() ISessionNoticeDo {
	return s.Clauses(dbresolver.Read)
}

func (s sessionNoticeDo) WriteDB() ISessionNoticeDo {
	return s.Clauses(dbresolver.Write)
}

func (s sessionNoticeDo) Session(config *gorm.Session) ISessionNoticeDo {
	return s.withDO(s.DO.Session(config))
}

func (s sessionNoticeDo) Clauses(conds ...clause.Expression) ISessionNoticeDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sessionNoticeDo) Returning(value interface{}, columns ...string) ISessionNoticeDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sessionNoticeDo) Not(conds ...gen.Condition) ISessionNoticeDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sessionNoticeDo) Or(conds ...gen.Condition) ISessionNoticeDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sessionNoticeDo) Select(conds ...field.Expr) ISessionNoticeDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sessionNoticeDo) Where(conds ...gen.Condition) ISessionNoticeDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sessionNoticeDo) Order(conds ...field.Expr) ISessionNoticeDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sessionNoticeDo) Distinct(cols ...field.Expr) ISessionNoticeDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sessionNoticeDo) Omit(cols ...field.Expr) ISessionNoticeDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sessionNoticeDo) Join(table schema.Tabler, on ...field.Expr) ISessionNoticeDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sessionNoticeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISessionNoticeDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sessionNoticeDo) RightJoin(table schema.Tabler, on ...field.Expr) ISessionNoticeDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sessionNoticeDo) Group(cols ...field.Expr) ISessionNoticeDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sessionNoticeDo) Having(conds ...gen.Condition) ISessionNoticeDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sessionNoticeDo) Limit(limit int) ISessionNoticeDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sessionNoticeDo) Offset(offset int) ISessionNoticeDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sessionNoticeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISessionNoticeDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sessionNoticeDo) Unscoped() ISessionNoticeDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sessionNoticeDo) Create(values ...*models.SessionNotice) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sessionNoticeDo) CreateInBatches(values []*models.SessionNotice, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sessionNoticeDo) Save(values ...*models.SessionNotice) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sessionNoticeDo) First() (*models.SessionNotice, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SessionNotice), nil
	}
}

func (s sessionNoticeDo) Take() (*models.SessionNotice, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SessionNotice), nil
	}
}

func (s sessionNoticeDo) Last() (*models.SessionNotice, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SessionNotice), nil
	}
}

func (s sessionNoticeDo) Find() ([]*models.SessionNotice, error) {
	result, err := s.DO.Find()
	return result.([]*models.SessionNotice), err
}

func (s sessionNoticeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SessionNotice, err error) {
	buf := make([]*models.SessionNotice, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sessionNoticeDo) FindInBatches(result *[]*models.SessionNotice, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sessionNoticeDo) Attrs(attrs ...field.AssignExpr) ISessionNoticeDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sessionNoticeDo) Assign(attrs ...field.AssignExpr) ISessionNoticeDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sessionNoticeDo) Joins(fields ...field.RelationField) ISessionNoticeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sessionNoticeDo) Preload(fields ...field.RelationField) ISessionNoticeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sessionNoticeDo) FirstOrInit() (*models.SessionNotice, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SessionNotice), nil
	}
}

func (s sessionNoticeDo) FirstOrCreate() (*models.SessionNotice, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SessionNotice), nil
	}
}

func (s sessionNoticeDo) FindByPage(offset int, limit int) (result []*models.SessionNotice, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sessionNoticeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sessionNoticeDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sessionNoticeDo) Delete(models ...*models.SessionNotice) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sessionNoticeDo) withDO(do gen.Dao) *sessionNoticeDo {
	s.DO = *do.(*gen.DO)
	return s
}
