// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/peen/internal/pkg/db/models"
)

func newSessionProfileDecision(db *gorm.DB, opts ...gen.DOOption) sessionProfileDecision {
	_sessionProfileDecision := sessionProfileDecision{}

	_sessionProfileDecision.sessionProfileDecisionDo.UseDB(db, opts...)
	_sessionProfileDecision.sessionProfileDecisionDo.UseModel(&models.SessionProfileDecision{})

	tableName := _sessionProfileDecision.sessionProfileDecisionDo.TableName()
	_sessionProfileDecision.ALL = field.NewAsterisk(tableName)
	_sessionProfileDecision.ID = field.NewField(tableName, "id")
	_sessionProfileDecision.SessionID = field.NewField(tableName, "session_id")
	_sessionProfileDecision.FromProfile = field.NewString(tableName, "from_profile")
	_sessionProfileDecision.ToProfile = field.NewString(tableName, "to_profile")
	_sessionProfileDecision.Reason = field.NewString(tableName, "reason")
	_sessionProfileDecision.DecidedAt = field.NewTime(tableName, "decided_at")

	_sessionProfileDecision.fillFieldMap()

	return _sessionProfileDecision
}

type sessionProfileDecision struct {
	sessionProfileDecisionDo

	ALL         field.Asterisk
	ID          field.Field
	SessionID   field.Field
	FromProfile field.String
	ToProfile   field.String
	Reason      field.String
	DecidedAt   field.Time

	fieldMap map[string]field.Expr
}

func (s sessionProfileDecision) Table(newTableName string) *sessionProfileDecision {
	s.sessionProfileDecisionDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sessionProfileDecision) As(alias string) *sessionProfileDecision {
	s.sessionProfileDecisionDo.DO = *(s.sessionProfileDecisionDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sessionProfileDecision) updateTableName(table string) *sessionProfileDecision {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewField(table, "id")
	s.SessionID = field.NewField(table, "session_id")
	s.FromProfile = field.NewString(table, "from_profile")
	s.ToProfile = field.NewString(table, "to_profile")
	s.Reason = field.NewString(table, "reason")
	s.DecidedAt = field.NewTime(table, "decided_at")

	s.fillFieldMap()

	return s
}

func (s *sessionProfileDecision) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sessionProfileDecision) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["id"] = s.ID
	s.fieldMap["session_id"] = s.SessionID
	s.fieldMap["from_profile"] = s.FromProfile
	s.fieldMap["to_profile"] = s.ToProfile
	s.fieldMap["reason"] = s.Reason
	s.fieldMap["decided_at"] = s.DecidedAt
}

func (s sessionProfileDecision) clone(db *gorm.DB) sessionProfileDecision {
	s.sessionProfileDecisionDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sessionProfileDecision) replaceDB(db *gorm.DB) sessionProfileDecision {
	s.sessionProfileDecisionDo.ReplaceDB(db)
	return s
}

type sessionProfileDecisionDo struct{ gen.DO }

type ISessionProfileDecisionDo interface {
	gen.SubQuery
	Debug() ISessionProfileDecisionDo
	WithContext(ctx context.Context) ISessionProfileDecisionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISessionProfileDecisionDo
	WriteDB() ISessionProfileDecisionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISessionProfileDecisionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISessionProfileDecisionDo
	Not(conds ...gen.Condition) ISessionProfileDecisionDo
	Or(conds ...gen.Condition) ISessionProfileDecisionDo
	Select(conds ...field.Expr) ISessionProfileDecisionDo
	Where(conds ...gen.Condition) ISessionProfileDecisionDo
	Order(conds ...field.Expr) ISessionProfileDecisionDo
	Distinct(cols ...field.Expr) ISessionProfileDecisionDo
	Omit(cols ...field.Expr) ISessionProfileDecisionDo
	Join(table schema.Tabler, on ...field.Expr) ISessionProfileDecisionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISessionProfileDecisionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISessionProfileDecisionDo
	Group(cols ...field.Expr) ISessionProfileDecisionDo
	Having(conds ...gen.Condition) ISessionProfileDecisionDo
	Limit(limit int) ISessionProfileDecisionDo
	Offset(offset int) ISessionProfileDecisionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISessionProfileDecisionDo
	Unscoped() ISessionProfileDecisionDo
	Create(values ...*models.SessionProfileDecision) error
	CreateInBatches(values []*models.SessionProfileDecision, batchSize int) error
	Save(values ...*models.SessionProfileDecision) error
	First() (*models.SessionProfileDecision, error)
	Take() (*models.SessionProfileDecision, error)
	Last() (*models.SessionProfileDecision, error)
	Find() ([]*models.SessionProfileDecision, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SessionProfileDecision, err error)
	FindInBatches(result *[]*models.SessionProfileDecision, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SessionProfileDecision) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISessionProfileDecisionDo
	Assign(attrs ...field.AssignExpr) ISessionProfileDecisionDo
	Joins(fields ...field.RelationField) ISessionProfileDecisionDo
	Preload(fields ...field.RelationField) ISessionProfileDecisionDo
	FirstOrInit() (*models.SessionProfileDecision, error)
	FirstOrCreate() (*models.SessionProfileDecision, error)
	FindByPage(offset int, limit int) (result []*models.SessionProfileDecision, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISessionProfileDecisionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sessionProfileDecisionDo) Debug() ISessionProfileDecisionDo {
	return s.withDO(s.DO.Debug())
}

func (s sessionProfileDecisionDo) WithContext(ctx context.Context) ISessionProfileDecisionDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sessionProfileDecisionDo) ReadDB() ISessionProfileDecisionDo {
	return s.Clauses(dbresolver.Read)
}

func (s sessionProfileDecisionDo) WriteDB() ISessionProfileDecisionDo {
	return s.Clauses(dbresolver.Write)
}

func (s sessionProfileDecisionDo) Session(config *gorm.Session) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Session(config))
}

func (s sessionProfileDecisionDo) Clauses(conds ...clause.Expression) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sessionProfileDecisionDo) Returning(value interface{}, columns ...string) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sessionProfileDecisionDo) Not(conds ...gen.Condition) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sessionProfileDecisionDo) Or(conds ...gen.Condition) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sessionProfileDecisionDo) Select(conds ...field.Expr) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sessionProfileDecisionDo) Where(conds ...gen.Condition) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sessionProfileDecisionDo) Order(conds ...field.Expr) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sessionProfileDecisionDo) Distinct(cols ...field.Expr) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sessionProfileDecisionDo) Omit(cols ...field.Expr) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sessionProfileDecisionDo) Join(table schema.Tabler, on ...field.Expr) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sessionProfileDecisionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISessionProfileDecisionDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sessionProfileDecisionDo) RightJoin(table schema.Tabler, on ...field.Expr) ISessionProfileDecisionDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sessionProfileDecisionDo) Group(cols ...field.Expr) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sessionProfileDecisionDo) Having(conds ...gen.Condition) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sessionProfileDecisionDo) Limit(limit int) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sessionProfileDecisionDo) Offset(offset int) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sessionProfileDecisionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sessionProfileDecisionDo) Unscoped() ISessionProfileDecisionDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sessionProfileDecisionDo) Create(values ...*models.SessionProfileDecision) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sessionProfileDecisionDo) CreateInBatches(values []*models.SessionProfileDecision, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sessionProfileDecisionDo) Save(values ...*models.SessionProfileDecision) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sessionProfileDecisionDo) First() (*models.SessionProfileDecision, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SessionProfileDecision), nil
	}
}

func (s sessionProfileDecisionDo) Take() (*models.SessionProfileDecision, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SessionProfileDecision), nil
	}
}

func (s sessionProfileDecisionDo) Last() (*models.SessionProfileDecision, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SessionProfileDecision), nil
	}
}

func (s sessionProfileDecisionDo) Find() ([]*models.SessionProfileDecision, error) {
	result, err := s.DO.Find()
	return result.([]*models.SessionProfileDecision), err
}

func (s sessionProfileDecisionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SessionProfileDecision, err error) {
	buf := make([]*models.SessionProfileDecision, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sessionProfileDecisionDo) FindInBatches(result *[]*models.SessionProfileDecision, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sessionProfileDecisionDo) Attrs(attrs ...field.AssignExpr) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sessionProfileDecisionDo) Assign(attrs ...field.AssignExpr) ISessionProfileDecisionDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sessionProfileDecisionDo) Joins(fields ...field.RelationField) ISessionProfileDecisionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sessionProfileDecisionDo) Preload(fields ...field.RelationField) ISessionProfileDecisionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sessionProfileDecisionDo) FirstOrInit() (*models.SessionProfileDecision, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SessionProfileDecision), nil
	}
}

func (s sessionProfileDecisionDo) FirstOrCreate() (*models.SessionProfileDecision, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SessionProfileDecision), nil
	}
}

func (s sessionProfileDecisionDo) FindByPage(offset int, limit int) (result []*models.SessionProfileDecision, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sessionProfileDecisionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sessionProfileDecisionDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sessionProfileDecisionDo) Delete(models ...*models.SessionProfileDecision) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sessionProfileDecisionDo) withDO(do gen.Dao) *sessionProfileDecisionDo {
	s.DO = *do.(*gen.DO)
	return s
}
