// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/peen/internal/pkg/db/models"
)

func newTurn(db *gorm.DB, opts ...gen.DOOption) turn {
	_turn := turn{}

	_turn.turnDo.UseDB(db, opts...)
	_turn.turnDo.UseModel(&models.Turn{})

	tableName := _turn.turnDo.TableName()
	_turn.ALL = field.NewAsterisk(tableName)
	_turn.ID = field.NewField(tableName, "id")
	_turn.SessionID = field.NewField(tableName, "session_id")
	_turn.RequestID = field.NewField(tableName, "request_id")
	_turn.Workspace = field.NewString(tableName, "workspace")
	_turn.State = field.NewString(tableName, "state")
	_turn.CancelRequested = field.NewBool(tableName, "cancel_requested")
	_turn.StartedAt = field.NewTime(tableName, "started_at")
	_turn.CompletedAt = field.NewTime(tableName, "completed_at")
	_turn.FailureClassification = field.NewString(tableName, "failure_classification")
	_turn.ContextSnapshotHash = field.NewString(tableName, "context_snapshot_hash")
	_turn.PromptSnapshotHash = field.NewString(tableName, "prompt_snapshot_hash")

	_turn.fillFieldMap()

	return _turn
}

type turn struct {
	turnDo

	ALL                   field.Asterisk
	ID                    field.Field
	SessionID             field.Field
	RequestID             field.Field
	Workspace             field.String
	State                 field.String
	CancelRequested       field.Bool
	StartedAt             field.Time
	CompletedAt           field.Time
	FailureClassification field.String
	ContextSnapshotHash   field.String
	PromptSnapshotHash    field.String

	fieldMap map[string]field.Expr
}

func (t turn) Table(newTableName string) *turn {
	t.turnDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t turn) As(alias string) *turn {
	t.turnDo.DO = *(t.turnDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *turn) updateTableName(table string) *turn {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewField(table, "id")
	t.SessionID = field.NewField(table, "session_id")
	t.RequestID = field.NewField(table, "request_id")
	t.Workspace = field.NewString(table, "workspace")
	t.State = field.NewString(table, "state")
	t.CancelRequested = field.NewBool(table, "cancel_requested")
	t.StartedAt = field.NewTime(table, "started_at")
	t.CompletedAt = field.NewTime(table, "completed_at")
	t.FailureClassification = field.NewString(table, "failure_classification")
	t.ContextSnapshotHash = field.NewString(table, "context_snapshot_hash")
	t.PromptSnapshotHash = field.NewString(table, "prompt_snapshot_hash")

	t.fillFieldMap()

	return t
}

func (t *turn) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *turn) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 11)
	t.fieldMap["id"] = t.ID
	t.fieldMap["session_id"] = t.SessionID
	t.fieldMap["request_id"] = t.RequestID
	t.fieldMap["workspace"] = t.Workspace
	t.fieldMap["state"] = t.State
	t.fieldMap["cancel_requested"] = t.CancelRequested
	t.fieldMap["started_at"] = t.StartedAt
	t.fieldMap["completed_at"] = t.CompletedAt
	t.fieldMap["failure_classification"] = t.FailureClassification
	t.fieldMap["context_snapshot_hash"] = t.ContextSnapshotHash
	t.fieldMap["prompt_snapshot_hash"] = t.PromptSnapshotHash
}

func (t turn) clone(db *gorm.DB) turn {
	t.turnDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t turn) replaceDB(db *gorm.DB) turn {
	t.turnDo.ReplaceDB(db)
	return t
}

type turnDo struct{ gen.DO }

type ITurnDo interface {
	gen.SubQuery
	Debug() ITurnDo
	WithContext(ctx context.Context) ITurnDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITurnDo
	WriteDB() ITurnDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITurnDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITurnDo
	Not(conds ...gen.Condition) ITurnDo
	Or(conds ...gen.Condition) ITurnDo
	Select(conds ...field.Expr) ITurnDo
	Where(conds ...gen.Condition) ITurnDo
	Order(conds ...field.Expr) ITurnDo
	Distinct(cols ...field.Expr) ITurnDo
	Omit(cols ...field.Expr) ITurnDo
	Join(table schema.Tabler, on ...field.Expr) ITurnDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITurnDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITurnDo
	Group(cols ...field.Expr) ITurnDo
	Having(conds ...gen.Condition) ITurnDo
	Limit(limit int) ITurnDo
	Offset(offset int) ITurnDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITurnDo
	Unscoped() ITurnDo
	Create(values ...*models.Turn) error
	CreateInBatches(values []*models.Turn, batchSize int) error
	Save(values ...*models.Turn) error
	First() (*models.Turn, error)
	Take() (*models.Turn, error)
	Last() (*models.Turn, error)
	Find() ([]*models.Turn, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Turn, err error)
	FindInBatches(result *[]*models.Turn, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Turn) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITurnDo
	Assign(attrs ...field.AssignExpr) ITurnDo
	Joins(fields ...field.RelationField) ITurnDo
	Preload(fields ...field.RelationField) ITurnDo
	FirstOrInit() (*models.Turn, error)
	FirstOrCreate() (*models.Turn, error)
	FindByPage(offset int, limit int) (result []*models.Turn, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITurnDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t turnDo) Debug() ITurnDo {
	return t.withDO(t.DO.Debug())
}

func (t turnDo) WithContext(ctx context.Context) ITurnDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t turnDo) ReadDB() ITurnDo {
	return t.Clauses(dbresolver.Read)
}

func (t turnDo) WriteDB() ITurnDo {
	return t.Clauses(dbresolver.Write)
}

func (t turnDo) Session(config *gorm.Session) ITurnDo {
	return t.withDO(t.DO.Session(config))
}

func (t turnDo) Clauses(conds ...clause.Expression) ITurnDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t turnDo) Returning(value interface{}, columns ...string) ITurnDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t turnDo) Not(conds ...gen.Condition) ITurnDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t turnDo) Or(conds ...gen.Condition) ITurnDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t turnDo) Select(conds ...field.Expr) ITurnDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t turnDo) Where(conds ...gen.Condition) ITurnDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t turnDo) Order(conds ...field.Expr) ITurnDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t turnDo) Distinct(cols ...field.Expr) ITurnDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t turnDo) Omit(cols ...field.Expr) ITurnDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t turnDo) Join(table schema.Tabler, on ...field.Expr) ITurnDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t turnDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITurnDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t turnDo) RightJoin(table schema.Tabler, on ...field.Expr) ITurnDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t turnDo) Group(cols ...field.Expr) ITurnDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t turnDo) Having(conds ...gen.Condition) ITurnDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t turnDo) Limit(limit int) ITurnDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t turnDo) Offset(offset int) ITurnDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t turnDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITurnDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t turnDo) Unscoped() ITurnDo {
	return t.withDO(t.DO.Unscoped())
}

func (t turnDo) Create(values ...*models.Turn) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t turnDo) CreateInBatches(values []*models.Turn, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t turnDo) Save(values ...*models.Turn) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t turnDo) First() (*models.Turn, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Turn), nil
	}
}

func (t turnDo) Take() (*models.Turn, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Turn), nil
	}
}

func (t turnDo) Last() (*models.Turn, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Turn), nil
	}
}

func (t turnDo) Find() ([]*models.Turn, error) {
	result, err := t.DO.Find()
	return result.([]*models.Turn), err
}

func (t turnDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Turn, err error) {
	buf := make([]*models.Turn, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t turnDo) FindInBatches(result *[]*models.Turn, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t turnDo) Attrs(attrs ...field.AssignExpr) ITurnDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t turnDo) Assign(attrs ...field.AssignExpr) ITurnDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t turnDo) Joins(fields ...field.RelationField) ITurnDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t turnDo) Preload(fields ...field.RelationField) ITurnDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t turnDo) FirstOrInit() (*models.Turn, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Turn), nil
	}
}

func (t turnDo) FirstOrCreate() (*models.Turn, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Turn), nil
	}
}

func (t turnDo) FindByPage(offset int, limit int) (result []*models.Turn, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t turnDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t turnDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t turnDo) Delete(models ...*models.Turn) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *turnDo) withDO(do gen.Dao) *turnDo {
	t.DO = *do.(*gen.DO)
	return t
}
