// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/peen/internal/pkg/db/models"
)

func newWorkerGeneration(db *gorm.DB, opts ...gen.DOOption) workerGeneration {
	_workerGeneration := workerGeneration{}

	_workerGeneration.workerGenerationDo.UseDB(db, opts...)
	_workerGeneration.workerGenerationDo.UseModel(&models.WorkerGeneration{})

	tableName := _workerGeneration.workerGenerationDo.TableName()
	_workerGeneration.ALL = field.NewAsterisk(tableName)
	_workerGeneration.ID = field.NewField(tableName, "id")
	_workerGeneration.SessionID = field.NewField(tableName, "session_id")
	_workerGeneration.Kind = field.NewString(tableName, "kind")
	_workerGeneration.Profile = field.NewString(tableName, "profile")
	_workerGeneration.ProfileRevision = field.NewInt64(tableName, "profile_revision")
	_workerGeneration.State = field.NewString(tableName, "state")
	_workerGeneration.Workspace = field.NewString(tableName, "workspace")
	_workerGeneration.CredentialHash = field.NewString(tableName, "credential_hash")
	_workerGeneration.SocketPath = field.NewString(tableName, "socket_path")
	_workerGeneration.ProcessID = field.NewInt(tableName, "process_id")
	_workerGeneration.ContainerID = field.NewString(tableName, "container_id")
	_workerGeneration.ImageDigest = field.NewString(tableName, "image_digest")
	_workerGeneration.FailureDetail = field.NewString(tableName, "failure_detail")
	_workerGeneration.ExitCode = field.NewInt(tableName, "exit_code")
	_workerGeneration.CreatedAt = field.NewTime(tableName, "created_at")
	_workerGeneration.StartedAt = field.NewTime(tableName, "started_at")
	_workerGeneration.EndedAt = field.NewTime(tableName, "ended_at")

	_workerGeneration.fillFieldMap()

	return _workerGeneration
}

type workerGeneration struct {
	workerGenerationDo

	ALL             field.Asterisk
	ID              field.Field
	SessionID       field.Field
	Kind            field.String
	Profile         field.String
	ProfileRevision field.Int64
	State           field.String
	Workspace       field.String
	CredentialHash  field.String
	SocketPath      field.String
	ProcessID       field.Int
	ContainerID     field.String
	ImageDigest     field.String
	FailureDetail   field.String
	ExitCode        field.Int
	CreatedAt       field.Time
	StartedAt       field.Time
	EndedAt         field.Time

	fieldMap map[string]field.Expr
}

func (w workerGeneration) Table(newTableName string) *workerGeneration {
	w.workerGenerationDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w workerGeneration) As(alias string) *workerGeneration {
	w.workerGenerationDo.DO = *(w.workerGenerationDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *workerGeneration) updateTableName(table string) *workerGeneration {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewField(table, "id")
	w.SessionID = field.NewField(table, "session_id")
	w.Kind = field.NewString(table, "kind")
	w.Profile = field.NewString(table, "profile")
	w.ProfileRevision = field.NewInt64(table, "profile_revision")
	w.State = field.NewString(table, "state")
	w.Workspace = field.NewString(table, "workspace")
	w.CredentialHash = field.NewString(table, "credential_hash")
	w.SocketPath = field.NewString(table, "socket_path")
	w.ProcessID = field.NewInt(table, "process_id")
	w.ContainerID = field.NewString(table, "container_id")
	w.ImageDigest = field.NewString(table, "image_digest")
	w.FailureDetail = field.NewString(table, "failure_detail")
	w.ExitCode = field.NewInt(table, "exit_code")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.StartedAt = field.NewTime(table, "started_at")
	w.EndedAt = field.NewTime(table, "ended_at")

	w.fillFieldMap()

	return w
}

func (w *workerGeneration) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *workerGeneration) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 17)
	w.fieldMap["id"] = w.ID
	w.fieldMap["session_id"] = w.SessionID
	w.fieldMap["kind"] = w.Kind
	w.fieldMap["profile"] = w.Profile
	w.fieldMap["profile_revision"] = w.ProfileRevision
	w.fieldMap["state"] = w.State
	w.fieldMap["workspace"] = w.Workspace
	w.fieldMap["credential_hash"] = w.CredentialHash
	w.fieldMap["socket_path"] = w.SocketPath
	w.fieldMap["process_id"] = w.ProcessID
	w.fieldMap["container_id"] = w.ContainerID
	w.fieldMap["image_digest"] = w.ImageDigest
	w.fieldMap["failure_detail"] = w.FailureDetail
	w.fieldMap["exit_code"] = w.ExitCode
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["started_at"] = w.StartedAt
	w.fieldMap["ended_at"] = w.EndedAt
}

func (w workerGeneration) clone(db *gorm.DB) workerGeneration {
	w.workerGenerationDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w workerGeneration) replaceDB(db *gorm.DB) workerGeneration {
	w.workerGenerationDo.ReplaceDB(db)
	return w
}

type workerGenerationDo struct{ gen.DO }

type IWorkerGenerationDo interface {
	gen.SubQuery
	Debug() IWorkerGenerationDo
	WithContext(ctx context.Context) IWorkerGenerationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWorkerGenerationDo
	WriteDB() IWorkerGenerationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWorkerGenerationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWorkerGenerationDo
	Not(conds ...gen.Condition) IWorkerGenerationDo
	Or(conds ...gen.Condition) IWorkerGenerationDo
	Select(conds ...field.Expr) IWorkerGenerationDo
	Where(conds ...gen.Condition) IWorkerGenerationDo
	Order(conds ...field.Expr) IWorkerGenerationDo
	Distinct(cols ...field.Expr) IWorkerGenerationDo
	Omit(cols ...field.Expr) IWorkerGenerationDo
	Join(table schema.Tabler, on ...field.Expr) IWorkerGenerationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWorkerGenerationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWorkerGenerationDo
	Group(cols ...field.Expr) IWorkerGenerationDo
	Having(conds ...gen.Condition) IWorkerGenerationDo
	Limit(limit int) IWorkerGenerationDo
	Offset(offset int) IWorkerGenerationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWorkerGenerationDo
	Unscoped() IWorkerGenerationDo
	Create(values ...*models.WorkerGeneration) error
	CreateInBatches(values []*models.WorkerGeneration, batchSize int) error
	Save(values ...*models.WorkerGeneration) error
	First() (*models.WorkerGeneration, error)
	Take() (*models.WorkerGeneration, error)
	Last() (*models.WorkerGeneration, error)
	Find() ([]*models.WorkerGeneration, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.WorkerGeneration, err error)
	FindInBatches(result *[]*models.WorkerGeneration, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.WorkerGeneration) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWorkerGenerationDo
	Assign(attrs ...field.AssignExpr) IWorkerGenerationDo
	Joins(fields ...field.RelationField) IWorkerGenerationDo
	Preload(fields ...field.RelationField) IWorkerGenerationDo
	FirstOrInit() (*models.WorkerGeneration, error)
	FirstOrCreate() (*models.WorkerGeneration, error)
	FindByPage(offset int, limit int) (result []*models.WorkerGeneration, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWorkerGenerationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w workerGenerationDo) Debug() IWorkerGenerationDo {
	return w.withDO(w.DO.Debug())
}

func (w workerGenerationDo) WithContext(ctx context.Context) IWorkerGenerationDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w workerGenerationDo) ReadDB() IWorkerGenerationDo {
	return w.Clauses(dbresolver.Read)
}

func (w workerGenerationDo) WriteDB() IWorkerGenerationDo {
	return w.Clauses(dbresolver.Write)
}

func (w workerGenerationDo) Session(config *gorm.Session) IWorkerGenerationDo {
	return w.withDO(w.DO.Session(config))
}

func (w workerGenerationDo) Clauses(conds ...clause.Expression) IWorkerGenerationDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w workerGenerationDo) Returning(value interface{}, columns ...string) IWorkerGenerationDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w workerGenerationDo) Not(conds ...gen.Condition) IWorkerGenerationDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w workerGenerationDo) Or(conds ...gen.Condition) IWorkerGenerationDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w workerGenerationDo) Select(conds ...field.Expr) IWorkerGenerationDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w workerGenerationDo) Where(conds ...gen.Condition) IWorkerGenerationDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w workerGenerationDo) Order(conds ...field.Expr) IWorkerGenerationDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w workerGenerationDo) Distinct(cols ...field.Expr) IWorkerGenerationDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w workerGenerationDo) Omit(cols ...field.Expr) IWorkerGenerationDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w workerGenerationDo) Join(table schema.Tabler, on ...field.Expr) IWorkerGenerationDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w workerGenerationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWorkerGenerationDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w workerGenerationDo) RightJoin(table schema.Tabler, on ...field.Expr) IWorkerGenerationDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w workerGenerationDo) Group(cols ...field.Expr) IWorkerGenerationDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w workerGenerationDo) Having(conds ...gen.Condition) IWorkerGenerationDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w workerGenerationDo) Limit(limit int) IWorkerGenerationDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w workerGenerationDo) Offset(offset int) IWorkerGenerationDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w workerGenerationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWorkerGenerationDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w workerGenerationDo) Unscoped() IWorkerGenerationDo {
	return w.withDO(w.DO.Unscoped())
}

func (w workerGenerationDo) Create(values ...*models.WorkerGeneration) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w workerGenerationDo) CreateInBatches(values []*models.WorkerGeneration, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w workerGenerationDo) Save(values ...*models.WorkerGeneration) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w workerGenerationDo) First() (*models.WorkerGeneration, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.WorkerGeneration), nil
	}
}

func (w workerGenerationDo) Take() (*models.WorkerGeneration, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.WorkerGeneration), nil
	}
}

func (w workerGenerationDo) Last() (*models.WorkerGeneration, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.WorkerGeneration), nil
	}
}

func (w workerGenerationDo) Find() ([]*models.WorkerGeneration, error) {
	result, err := w.DO.Find()
	return result.([]*models.WorkerGeneration), err
}

func (w workerGenerationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.WorkerGeneration, err error) {
	buf := make([]*models.WorkerGeneration, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w workerGenerationDo) FindInBatches(result *[]*models.WorkerGeneration, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w workerGenerationDo) Attrs(attrs ...field.AssignExpr) IWorkerGenerationDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w workerGenerationDo) Assign(attrs ...field.AssignExpr) IWorkerGenerationDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w workerGenerationDo) Joins(fields ...field.RelationField) IWorkerGenerationDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w workerGenerationDo) Preload(fields ...field.RelationField) IWorkerGenerationDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w workerGenerationDo) FirstOrInit() (*models.WorkerGeneration, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.WorkerGeneration), nil
	}
}

func (w workerGenerationDo) FirstOrCreate() (*models.WorkerGeneration, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.WorkerGeneration), nil
	}
}

func (w workerGenerationDo) FindByPage(offset int, limit int) (result []*models.WorkerGeneration, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w workerGenerationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w workerGenerationDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w workerGenerationDo) Delete(models ...*models.WorkerGeneration) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *workerGenerationDo) withDO(do gen.Dao) *workerGenerationDo {
	w.DO = *do.(*gen.DO)
	return w
}
